# LIAR Fake News Detection - Novel LIAR-Only Optimization v7

Binary-focused original LIAR run. This version fixes original/refit probability overwriting, adds a LIAR credibility calibrator into the ensemble, keeps the metadata GNN fusion, and writes fresh v7 result folders. No LIAR-PLUS evidence is used.

In [1]:
# Run this setup cell once if a package is missing in your Jupyter kernel.
%pip install pandas numpy scipy seaborn matplotlib spacy wordcloud nltk scikit-learn transformers datasets accelerate sentence-transformers torch tqdm sentencepiece
%pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl

Requirement already satisfied: pandas in .\venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in .\venv\lib\site-packages (2.2.6)
Requirement already satisfied: scipy in .\venv\lib\site-packages (1.15.3)
Requirement already satisfied: seaborn in .\venv\lib\site-packages (0.13.2)
Requirement already satisfied: matplotlib in .\venv\lib\site-packages (3.10.9)
Requirement already satisfied: spacy in .\venv\lib\site-packages (3.8.14)
Requirement already satisfied: wordcloud in .\venv\lib\site-packages (1.9.6)
Requirement already satisfied: nltk in .\venv\lib\site-packages (3.9.4)
Requirement already satisfied: scikit-learn in .\venv\lib\site-packages (1.7.2)
Requirement already satisfied: transformers in .\venv\lib\site-packages (5.9.0)
Requirement already satisfied: datasets in .\venv\lib\site-packages (4.8.5)
Requirement already satisfied: accelerate in .\venv\lib\site-packages (1.13.0)
Requirement already satisfied: sentence-transformers in .\venv\lib\site-packages (5.5.1)
Requirement already satisfied: torch in .\venv\lib\site-packages (2.5.1+cu121)
Requirement already satisfied: tqdm in .\venv\lib\site-packages (4.67.3)
Requirement already satisfied: sentencepiece in .\venv\lib\site-packages (0.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in .\venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in .\venv\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in .\venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\venv\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\venv\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\venv\lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in .\venv\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in .\venv\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in .\venv\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in .\venv\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in .\venv\lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in .\venv\lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in .\venv\lib\site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in .\venv\lib\site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in .\venv\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in .\venv\lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in .\venv\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in .\venv\lib\site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in .\venv\lib\site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in .\venv\lib\site-packages (from spacy) (0.25.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in .\venv\lib\site-packages (from spacy) (2.34.2)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in .\venv\lib\site-packages (from spacy) (2.13.4)
Requirement already satisfied: jinja2 in .\venv\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in .\venv\lib\site-packages (from spacy) (65.5.0)
Requirement already satisfied: colorama in .\venv\lib\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: typing_extensions<5.0,>=4.0 in .\venv\lib\site-packages (from confection<2.0.0,>=1.3.2->spacy) (4.15.0)
Requirement already satisfied: annotated-types>=0.6.0 in .\venv\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in .\venv\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in .\venv\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in .\venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in .\venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.17)
Requirement already satisfied: urllib3<3,>=1.26 in .\venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in .\venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.5.20)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in .\venv\lib\site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: click>=8.2.1 in .\venv\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.4.1)
Requirement already satisfied: shellingham>=1.3.0 in .\venv\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in .\venv\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in .\venv\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in .\venv\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in .\venv\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.6.1)
Requirement already satisfied: httpx>=0.24.0 in .\venv\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: joblib in .\venv\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in .\venv\lib\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: threadpoolctl>=3.1.0 in .\venv\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in .\venv\lib\site-packages (from transformers) (1.17.0)
Requirement already satisfied: pyyaml>=5.1 in .\venv\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in .\venv\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in .\venv\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in .\venv\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in .\venv\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in .\venv\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.0)
Requirement already satisfied: anyio in .\venv\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.13.0)
Requirement already satisfied: httpcore==1.* in .\venv\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in .\venv\lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: pyarrow>=21.0.0 in .\venv\lib\site-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in .\venv\lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: xxhash in .\venv\lib\site-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in .\venv\lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in .\venv\lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: psutil in .\venv\lib\site-packages (from accelerate) (7.2.2)
Requirement already satisfied: networkx in .\venv\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: sympy==1.13.1 in .\venv\lib\site-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in .\venv\lib\site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in .\venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in .\venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in .\venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in .\venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in .\venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in .\venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in .\venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in .\venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: six>=1.5 in .\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\venv\lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\venv\lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in .\venv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: wrapt in .\venv\lib\site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.2.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in .\venv\lib\site-packages (from anyio->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in .\venv\lib\site-packages (from jinja2->spacy) (3.0.3)
Note: you may need to restart the kernel to use updated packages.
Collecting en-core-web-sm==3.8.0
  Downloading en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
     - ------------------------------------- 0.5/12.8 MB 840.2 kB/s eta 0:00:15
     -- ------------------------------------- 0.8/12.8 MB 1.0 MB/s eta 0:00:12
     --- ------------------------------------ 1.0/12.8 MB 1.1 MB/s eta 0:00:11
     ---- ----------------------------------- 1.3/12.8 MB 1.2 MB/s eta 0:00:10
     ---- ----------------------------------- 1.3/12.8 MB 1.2 MB/s eta 0:00:10
     ---- ----------------------------------- 1.6/12.8 MB 1.0 MB/s eta 0:00:12
     ---- ----------------------------------- 1.6/12.8 MB 1.0 MB/s eta 0:00:12
     ----- --------------------------------- 1.8/12.8 MB 915.5 kB/s eta 0:00:12
     ------ -------------------------------- 2.1/12.8 MB 947.3 kB/s eta 0:00:12
     ------- ------------------------------- 2.4/12.8 MB 980.0 kB/s eta 0:00:11
     -------- ------------------------------- 2.6/12.8 MB 1.0 MB/s eta 0:00:10
     --------- ------------------------------ 2.9/12.8 MB 1.0 MB/s eta 0:00:10
     --------- ------------------------------ 3.1/12.8 MB 1.0 MB/s eta 0:00:10
     ---------- ----------------------------- 3.4/12.8 MB 1.1 MB/s eta 0:00:09
     ---------- ----------------------------- 3.4/12.8 MB 1.1 MB/s eta 0:00:09
     ----------- ---------------------------- 3.7/12.8 MB 1.0 MB/s eta 0:00:09
     ----------- ---------------------------- 3.7/12.8 MB 1.0 MB/s eta 0:00:09
     ----------- --------------------------- 3.9/12.8 MB 955.0 kB/s eta 0:00:10
     ----------- --------------------------- 3.9/12.8 MB 955.0 kB/s eta 0:00:10
     ------------ -------------------------- 4.2/12.8 MB 918.5 kB/s eta 0:00:10
     ------------- ------------------------- 4.5/12.8 MB 910.0 kB/s eta 0:00:10
     ------------- ------------------------- 4.5/12.8 MB 910.0 kB/s eta 0:00:10
     ------------- ------------------------- 4.5/12.8 MB 910.0 kB/s eta 0:00:10
     -------------- ------------------------ 4.7/12.8 MB 872.3 kB/s eta 0:00:10
     -------------- ------------------------ 4.7/12.8 MB 872.3 kB/s eta 0:00:10
     --------------- ----------------------- 5.2/12.8 MB 883.1 kB/s eta 0:00:09
     ---------------- ---------------------- 5.5/12.8 MB 892.4 kB/s eta 0:00:09
     ----------------- --------------------- 5.8/12.8 MB 912.8 kB/s eta 0:00:08
     ------------------- ------------------- 6.3/12.8 MB 957.5 kB/s eta 0:00:07
     --------------------- ------------------ 6.8/12.8 MB 1.0 MB/s eta 0:00:06
     ---------------------- ----------------- 7.3/12.8 MB 1.1 MB/s eta 0:00:06
     ----------------------- ---------------- 7.6/12.8 MB 1.1 MB/s eta 0:00:05
     ------------------------ --------------- 7.9/12.8 MB 1.1 MB/s eta 0:00:05
     -------------------------- ------------- 8.4/12.8 MB 1.1 MB/s eta 0:00:04
     -------------------------- ------------- 8.4/12.8 MB 1.1 MB/s eta 0:00:04
     -------------------------- ------------- 8.4/12.8 MB 1.1 MB/s eta 0:00:04
     --------------------------- ------------ 8.9/12.8 MB 1.1 MB/s eta 0:00:04
     ---------------------------- ----------- 9.2/12.8 MB 1.1 MB/s eta 0:00:04
     ----------------------------- ---------- 9.4/12.8 MB 1.1 MB/s eta 0:00:04
     ------------------------------- -------- 10.0/12.8 MB 1.1 MB/s eta 0:00:03
     ------------------------------- -------- 10.2/12.8 MB 1.1 MB/s eta 0:00:03
     --------------------------------- ------ 10.7/12.8 MB 1.2 MB/s eta 0:00:02
     --------------------------------- ------ 10.7/12.8 MB 1.2 MB/s eta 0:00:02
     --------------------------------- ------ 10.7/12.8 MB 1.2 MB/s eta 0:00:02
     ---------------------------------- ----- 11.0/12.8 MB 1.1 MB/s eta 0:00:02
     ---------------------------------- ----- 11.0/12.8 MB 1.1 MB/s eta 0:00:02
     ---------------------------------- ----- 11.0/12.8 MB 1.1 MB/s eta 0:00:02
     ----------------------------------- ---- 11.3/12.8 MB 1.1 MB/s eta 0:00:02
     ----------------------------------- ---- 11.3/12.8 MB 1.1 MB/s eta 0:00:02
     ------------------------------------ --- 11.5/12.8 MB 1.1 MB/s eta 0:00:02
     ------------------------------------ --- 11.5/12.8 MB 1.1 MB/s eta 0:00:02
     ------------------------------------ --- 11.8/12.8 MB 1.1 MB/s eta 0:00:01
     ------------------------------------ --- 11.8/12.8 MB 1.1 MB/s eta 0:00:01
     ------------------------------------- -- 12.1/12.8 MB 1.0 MB/s eta 0:00:01
     ------------------------------------- -- 12.1/12.8 MB 1.0 MB/s eta 0:00:01
     -------------------------------------- - 12.3/12.8 MB 1.0 MB/s eta 0:00:01
     -------------------------------------- - 12.3/12.8 MB 1.0 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 1.0 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 996.1 kB/s  0:00:12
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"
import re
import json
import inspect
import random
import shutil
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import nltk
import spacy

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    precision_recall_fscore_support,
    recall_score,
    f1_score,
)
from sklearn.utils.class_weight import compute_class_weight
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import FeatureUnion
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    DataCollatorWithPadding,
    EarlyStoppingCallback,
    Trainer,
    TrainingArguments,
    set_seed,
)

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)
set_seed(SEED)

nltk.download("stopwords")
nlp = spacy.load("en_core_web_sm")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

C:\Users\Asus\Downloads\Fake news detection\code\venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Device: cuda
GPU: NVIDIA GeForce RTX 2060

In [3]:
PROJECT_DIR = Path(r"C:\Users\Asus\Downloads\Fake news detection\code")
DATA_DIR = PROJECT_DIR / "dataset"
RESULTS_DIR = PROJECT_DIR / "optimized_results_simple_liar_novel_v7"
LOGS_DIR = PROJECT_DIR / "optimized_logs_simple_liar_novel_v7"
SUMMARY_DIR = PROJECT_DIR / "optimized_summaries_simple_liar_novel_v7"

for path in [RESULTS_DIR, LOGS_DIR, SUMMARY_DIR]:
    path.mkdir(parents=True, exist_ok=True)

RUN_VERSION = "v7"
print(f"Running notebook version: {RUN_VERSION}")
print(f"Results folder: {RESULTS_DIR}")

# Fresh retrain only. No older weight folders are pooled in v7.
EXTRA_LIAR_RESULT_DIRS = []

LIAR_COLUMNS = [
    "Id",
    "Label",
    "Statement",
    "Subject",
    "Speaker",
    "Job Title",
    "State",
    "Party",
    "Barely True Counts",
    "False Counts",
    "Half True Counts",
    "Mostly True Counts",
    "Pants on Fire Counts",
    "Context",
]


def load_liar_split(split_name):
    df = pd.read_csv(DATA_DIR / f"{split_name}.csv")
    df.columns = LIAR_COLUMNS
    df["split"] = split_name
    return df

train_raw = load_liar_split("train")
valid_raw = load_liar_split("valid")
test_raw = load_liar_split("test")

for split_name, df in [("train", train_raw), ("valid", valid_raw), ("test", test_raw)]:
    print(f"{split_name}: {df.shape}")
    print(df["Label"].value_counts().sort_index())
    print()

Running notebook version: v7
Results folder: C:\Users\Asus\Downloads\Fake news detection\code\optimized_results_simple_liar_novel_v7
train: (10269, 15)
Label
barely-true    1657
false          1998
half-true      2123
mostly-true    1966
pants-fire      842
true           1683
Name: count, dtype: int64

valid: (1284, 15)
Label
barely-true    237
false          263
half-true      248
mostly-true    251
pants-fire     116
true           169
Name: count, dtype: int64

test: (1283, 15)
Label
barely-true    214
false          250
half-true      267
mostly-true    249
pants-fire      92
true           211
Name: count, dtype: int64

In [4]:
# Paper-inspired LIAR input: combine statement + metadata.
# For transformer models, keep this light. Do not remove stopwords, punctuation, or numbers.
COUNT_COLUMNS = [
    "Barely True Counts",
    "False Counts",
    "Half True Counts",
    "Mostly True Counts",
    "Pants on Fire Counts",
]
TEXT_METADATA_COLUMNS = ["Subject", "Speaker", "Job Title", "State", "Party", "Context"]


def clean_field(value):
    if pd.isna(value):
        return ""
    text = str(value).strip()
    if text in {"\\N", "nan", "None", "null"}:
        return ""
    return re.sub(r"\s+", " ", text)


def build_liar_text(row, include_history_counts=True):
    parts = []

    statement = clean_field(row["Statement"])
    if statement:
        parts.append(f"statement: {statement}")

    for col in TEXT_METADATA_COLUMNS:
        value = clean_field(row[col])
        if value:
            parts.append(f"{col.lower()}: {value}")

    if include_history_counts:
        counts = []
        count_names = {
            "Barely True Counts": "barely_true",
            "False Counts": "false",
            "Half True Counts": "half_true",
            "Mostly True Counts": "mostly_true",
            "Pants on Fire Counts": "pants_fire",
        }
        for col, name in count_names.items():
            value = row[col]
            if pd.notna(value):
                counts.append(f"{name}={int(value)}")
        if counts:
            parts.append("speaker_history: " + " ".join(counts))

    return " ".join(parts)


def add_model_text(df):
    df = df.copy()
    df["model_text"] = df.apply(build_liar_text, axis=1)
    df["text_length"] = df["model_text"].str.split().str.len()
    return df

train_df = add_model_text(train_raw)
valid_df = add_model_text(valid_raw)
test_df = add_model_text(test_raw)

print(train_df[["Label", "model_text", "text_length"]].head(3).to_string(index=False))
print("\nLength summary:")
print(pd.concat([train_df, valid_df, test_df])["text_length"].describe())

      Label                                                                                                                                                                                                                                                                                                                                                                                    model_text  text_length
      false                                                                                          statement: Says the Annies List political group supports third-trimester abortions on demand. subject: abortion speaker: dwayne-bohac job title: State representative state: Texas party: republican context: a mailer speaker_history: barely_true=0 false=1 half_true=0 mostly_true=0 pants_fire=0           33
  half-true statement: When did the decline of coal start? It started when natural gas took off that started to begin in (President George W.) Bushs administration. subject: energy,history,job-accomplishments speaker: scott-surovell job title: State delegate state: Virginia party: democrat context: a floor speech. speaker_history: barely_true=0 false=0 half_true=1 mostly_true=1 pants_fire=0           47
mostly-true                                                                   statement: Hillary Clinton agrees with John McCain "by voting to give George Bush the benefit of the doubt on Iran." subject: foreign-policy speaker: barack-obama job title: President state: Illinois party: democrat context: Denver speaker_history: barely_true=70 false=71 half_true=160 mostly_true=163 pants_fire=9           39

Length summary:
count    12836.000000
mean        41.326893
std          8.918242
min         16.000000
25%         35.000000
50%         40.000000
75%         47.000000
max         87.000000
Name: text_length, dtype: float64

In [5]:
# Binary mapping follows the paper: false/barely-true/pants-fire = fake, half/mostly/true = real.
BINARY_MAP = {
    "pants-fire": 0,
    "false": 0,
    "barely-true": 0,
    "half-true": 1,
    "mostly-true": 1,
    "true": 1,
}
BINARY_LABEL_NAMES = ["fake", "real"]

MULTICLASS_MAP = {
    "pants-fire": 0,
    "false": 1,
    "barely-true": 2,
    "half-true": 3,
    "mostly-true": 4,
    "true": 5,
}
MULTICLASS_LABEL_NAMES = ["pants-fire", "false", "barely-true", "half-true", "mostly-true", "true"]

# Hierarchical multiclass setup for simple LIAR:
# binary fake/real gate, then a fake-subtype classifier and a real-subtype classifier.
FAKE_SUBTYPE_MAP = {
    "pants-fire": 0,
    "false": 1,
    "barely-true": 2,
}
FAKE_SUBTYPE_LABEL_NAMES = ["pants-fire", "false", "barely-true"]

REAL_SUBTYPE_MAP = {
    "half-true": 0,
    "mostly-true": 1,
    "true": 2,
}
REAL_SUBTYPE_LABEL_NAMES = ["half-true", "mostly-true", "true"]


def make_task_splits(label_map):
    splits = {}
    for split_name, df in [("train", train_df), ("valid", valid_df), ("test", test_df)]:
        task_df = df.copy()
        task_df["label"] = task_df["Label"].map(label_map)
        task_df = task_df.dropna(subset=["label", "model_text"])
        task_df["label"] = task_df["label"].astype(int)
        splits[split_name] = {
            "texts": task_df["model_text"].tolist(),
            "labels": task_df["label"].to_numpy(dtype=np.int64),
            "frame": task_df,
        }
    return splits


binary_splits = make_task_splits(BINARY_MAP)
multiclass_splits = make_task_splits(MULTICLASS_MAP)
fake_subtype_splits = make_task_splits(FAKE_SUBTYPE_MAP)
real_subtype_splits = make_task_splits(REAL_SUBTYPE_MAP)



def make_binary_nested_refit_splits(label_map, inner_valid_size=0.08):
    # Original LIAR only: use original valid as additional training data,
    # while holding out a small inner validation split from original train for early stopping/calibration.
    train_task = train_df.copy()
    train_task["label"] = train_task["Label"].map(label_map)
    train_task = train_task.dropna(subset=["label", "model_text"]).copy()
    train_task["label"] = train_task["label"].astype(int)

    original_valid_task = valid_df.copy()
    original_valid_task["label"] = original_valid_task["Label"].map(label_map)
    original_valid_task = original_valid_task.dropna(subset=["label", "model_text"]).copy()
    original_valid_task["label"] = original_valid_task["label"].astype(int)

    inner_train_df, inner_valid_df = train_test_split(
        train_task,
        test_size=inner_valid_size,
        stratify=train_task["label"],
        random_state=SEED,
    )
    final_train_df = pd.concat([inner_train_df, original_valid_task], ignore_index=True)

    test_task = test_df.copy()
    test_task["label"] = test_task["Label"].map(label_map)
    test_task = test_task.dropna(subset=["label", "model_text"]).copy()
    test_task["label"] = test_task["label"].astype(int)

    return {
        "train": to_split_payload(final_train_df),
        "valid": to_split_payload(inner_valid_df),
        "test": to_split_payload(test_task),
    }


def to_split_payload(task_df):
    return {
        "texts": task_df["model_text"].tolist(),
        "labels": task_df["label"].to_numpy(dtype=np.int64),
        "frame": task_df.reset_index(drop=True),
    }


binary_refit_splits = make_binary_nested_refit_splits(BINARY_MAP, inner_valid_size=0.08)

for task_name, splits, names in [
    ("binary", binary_splits, BINARY_LABEL_NAMES),
    ("multiclass", multiclass_splits, MULTICLASS_LABEL_NAMES),
    ("fake_subtype", fake_subtype_splits, FAKE_SUBTYPE_LABEL_NAMES),
    ("real_subtype", real_subtype_splits, REAL_SUBTYPE_LABEL_NAMES),
]:
    print(f"\n{task_name.upper()} distributions")
    for split_name in ["train", "valid", "test"]:
        labels = pd.Series(splits[split_name]["labels"]).map(dict(enumerate(names)))
        print(split_name)
        print(labels.value_counts().reindex(names, fill_value=0))

BINARY distributions
train
fake    4497
real    5772
Name: count, dtype: int64
valid
fake    616
real    668
Name: count, dtype: int64
test
fake    556
real    727
Name: count, dtype: int64

MULTICLASS distributions
train
pants-fire      842
false          1998
barely-true    1657
half-true      2123
mostly-true    1966
true           1683
Name: count, dtype: int64
valid
pants-fire     116
false          263
barely-true    237
half-true      248
mostly-true    251
true           169
Name: count, dtype: int64
test
pants-fire      92
false          250
barely-true    214
half-true      267
mostly-true    249
true           211
Name: count, dtype: int64

FAKE_SUBTYPE distributions
train
pants-fire      842
false          1998
barely-true    1657
Name: count, dtype: int64
valid
pants-fire     116
false          263
barely-true    237
Name: count, dtype: int64
test
pants-fire      92
false          250
barely-true    214
Name: count, dtype: int64

REAL_SUBTYPE distributions
train
half-true      2123
mostly-true    1966
true           1683
Name: count, dtype: int64
valid
half-true      248
mostly-true    251
true           169
Name: count, dtype: int64
test
half-true      267
mostly-true    249
true           211
Name: count, dtype: int64

In [6]:
def make_compute_metrics(task_name, label_names):
    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=-1)
        metrics = {
            "accuracy": accuracy_score(labels, preds),
            "macro_recall": recall_score(labels, preds, average="macro", zero_division=0),
            "weighted_recall": recall_score(labels, preds, average="weighted", zero_division=0),
            "macro_f1": f1_score(labels, preds, average="macro", zero_division=0),
            "weighted_f1": f1_score(labels, preds, average="weighted", zero_division=0),
        }
        if task_name == "binary":
            metrics["fake_recall"] = recall_score(labels, preds, pos_label=0, zero_division=0)
            metrics["real_recall"] = recall_score(labels, preds, pos_label=1, zero_division=0)
        return metrics
    return compute_metrics


def summarize_predictions(y_true, y_pred, label_names, task_name):
    summary = make_compute_metrics(task_name, label_names)((None, y_true)) if False else {}
    summary.update({
        "accuracy": accuracy_score(y_true, y_pred),
        "macro_recall": recall_score(y_true, y_pred, average="macro", zero_division=0),
        "weighted_recall": recall_score(y_true, y_pred, average="weighted", zero_division=0),
        "macro_f1": f1_score(y_true, y_pred, average="macro", zero_division=0),
        "weighted_f1": f1_score(y_true, y_pred, average="weighted", zero_division=0),
    })
    if task_name == "binary":
        summary["fake_recall"] = recall_score(y_true, y_pred, pos_label=0, zero_division=0)
        summary["real_recall"] = recall_score(y_true, y_pred, pos_label=1, zero_division=0)
    return summary


def print_report(title, y_true, y_pred, label_names, task_name):
    print("\n" + title)
    summary = summarize_predictions(y_true, y_pred, label_names, task_name)
    print(pd.Series(summary).round(4).to_string())
    print(classification_report(y_true, y_pred, target_names=label_names, zero_division=0))
    return summary

In [7]:
class FakeNewsDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = [int(x) for x in labels]

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

    def __len__(self):
        return len(self.labels)


class WeightedLossTrainer(Trainer):
    def __init__(self, class_weights=None, label_smoothing=0.0, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_weights = class_weights
        self.label_smoothing = float(label_smoothing)

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits
        weights = self.class_weights.to(logits.device) if self.class_weights is not None else None
        loss_fct = torch.nn.CrossEntropyLoss(weight=weights, label_smoothing=self.label_smoothing)
        loss = loss_fct(logits.view(-1, model.config.num_labels), labels.view(-1))
        return (loss, outputs) if return_outputs else loss


def encode_texts(tokenizer, texts, labels, max_length=128):
    encodings = tokenizer(texts, truncation=True, max_length=max_length)
    return FakeNewsDataset(encodings, labels)


def model_safe_name(model_name):
    return model_name.replace("/", "_").replace("-", "_").replace(".", "_")


def local_model_ready(path):
    path = Path(path)
    model_file_exists = (path / "model.safetensors").exists() or (path / "pytorch_model.bin").exists()
    tokenizer_exists = any((path / name).exists() for name in ["tokenizer.json", "vocab.txt", "merges.txt", "sentencepiece.bpe.model", "spiece.model", "spm.model"])
    return (path / "config.json").exists() and model_file_exists and tokenizer_exists


def get_class_weights(labels, num_labels):
    classes = np.arange(num_labels)
    weights = compute_class_weight(class_weight="balanced", classes=classes, y=np.asarray(labels))
    return torch.tensor(weights, dtype=torch.float32)


def cleanup_checkpoints(run_dir):
    run_dir = Path(run_dir)
    for checkpoint_dir in run_dir.glob("checkpoint-*"):
        if checkpoint_dir.is_dir():
            shutil.rmtree(checkpoint_dir, ignore_errors=True)


# Conservative simple-LIAR tuning: safe default models, early stopping,
# validation-selected checkpointing, and optional slow candidates kept out of the automatic run.

MODEL_CONFIGS = {
    "distilbert-base-uncased": {"learning_rate": 3e-5, "epochs": 2, "batch_size": 16, "grad_accum": 1, "max_length": 128, "eval_batch_size": 32, "use_safetensors": True, "label_smoothing": 0.0, "early_stop": 1},
    "bert-base-uncased": {"learning_rate": 3e-5, "epochs": 2, "batch_size": 16, "grad_accum": 1, "max_length": 128, "eval_batch_size": 32, "use_safetensors": True, "label_smoothing": 0.0, "early_stop": 1},
    "roberta-base": {"learning_rate": 2e-5, "epochs": 2, "batch_size": 16, "grad_accum": 1, "max_length": 128, "eval_batch_size": 32, "use_safetensors": True, "label_smoothing": 0.0, "early_stop": 1},
    "distilroberta-base": {"learning_rate": 2e-5, "epochs": 3, "batch_size": 16, "grad_accum": 1, "max_length": 128, "eval_batch_size": 32, "use_safetensors": True, "label_smoothing": 0.0, "early_stop": 1},
    "albert-base-v2": {"learning_rate": 2e-5, "epochs": 3, "batch_size": 16, "grad_accum": 1, "max_length": 128, "eval_batch_size": 32, "use_safetensors": True, "label_smoothing": 0.0, "early_stop": 1},
    "albert-large-v2": {"learning_rate": 1e-5, "epochs": 3, "batch_size": 4, "grad_accum": 4, "max_length": 128, "eval_batch_size": 8, "use_safetensors": True, "label_smoothing": 0.0, "early_stop": 1},
    "roberta-large": {"learning_rate": 7e-6, "epochs": 2, "batch_size": 2, "grad_accum": 16, "max_length": 128, "eval_batch_size": 4, "use_safetensors": True, "label_smoothing": 0.0, "early_stop": 1},
}

PAPER_MODELS = ["distilbert-base-uncased", "bert-base-uncased", "roberta-base"]
ADDITIONAL_LIAR_TRANSFORMERS = []
DEFAULT_MODELS = PAPER_MODELS + ADDITIONAL_LIAR_TRANSFORMERS
BINARY_HIGH_ACCURACY_MODELS = DEFAULT_MODELS
BINARY_REFIT_MODELS = ["distilbert-base-uncased", "bert-base-uncased", "roberta-base"]
OPTIONAL_SLOW_MODELS = ["distilroberta-base", "albert-base-v2", "albert-large-v2", "roberta-large"]
HIERARCHICAL_MODELS = ["distilbert-base-uncased"]

In [8]:
def torch_version_tuple():
    base = torch.__version__.split("+")[0]
    parts = []
    for piece in base.split(".")[:3]:
        try:
            parts.append(int(piece))
        except ValueError:
            parts.append(0)
    while len(parts) < 3:
        parts.append(0)
    return tuple(parts)


def torch_can_load_bin_weights():
    return torch_version_tuple() >= (2, 6, 0)


def estimate_warmup_steps(num_examples, batch_size, grad_accum, epochs):
    effective_batch = max(1, int(batch_size) * int(grad_accum))
    steps_per_epoch = max(1, int(np.ceil(num_examples / effective_batch)))
    total_steps = max(1, steps_per_epoch * int(np.ceil(epochs)))
    return min(150, max(10, int(0.08 * total_steps)))


def make_training_arguments(**kwargs):
    supported = set(inspect.signature(TrainingArguments.__init__).parameters)
    args = dict(kwargs)
    if "eval_strategy" in args and "eval_strategy" not in supported and "evaluation_strategy" in supported:
        args["evaluation_strategy"] = args.pop("eval_strategy")
    filtered = {key: value for key, value in args.items() if key in supported}
    skipped = sorted(set(args) - supported)
    if skipped:
        print("Skipping unsupported TrainingArguments:", skipped)
    return TrainingArguments(**filtered)


def build_weighted_trainer(tokenizer, **kwargs):
    supported = set(inspect.signature(Trainer.__init__).parameters)
    if "processing_class" in supported:
        kwargs["processing_class"] = tokenizer
    elif "tokenizer" in supported:
        kwargs["tokenizer"] = tokenizer
    return WeightedLossTrainer(**kwargs)


def train_or_load_transformer(
    model_name,
    splits,
    task_name,
    label_names,
    force_retrain=False,
    use_class_weights=True,
):
    config = MODEL_CONFIGS[model_name]
    num_labels = len(label_names)
    run_dir = RESULTS_DIR / f"{model_safe_name(model_name)}_{task_name}"
    if force_retrain and run_dir.exists():
        shutil.rmtree(run_dir, ignore_errors=True)
    run_dir.mkdir(parents=True, exist_ok=True)

    source = str(run_dir) if local_model_ready(run_dir) and not force_retrain else model_name
    if source == str(run_dir):
        print(f"Loading existing optimized model: {run_dir}")
    else:
        print(f"Training {model_name} for {task_name} -> {run_dir}")

    if config.get("requires_torch_26") and not torch_can_load_bin_weights():
        print(f"Skipping {model_name}: this model requires torch>=2.6 in the current transformers setup.")
        return {"model_name": model_name, "task_name": task_name, "run_dir": run_dir, "skipped": True}

    tokenizer = AutoTokenizer.from_pretrained(source)
    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

    train_dataset = encode_texts(tokenizer, splits["train"]["texts"], splits["train"]["labels"], config["max_length"])
    valid_dataset = encode_texts(tokenizer, splits["valid"]["texts"], splits["valid"]["labels"], config["max_length"])
    test_dataset = encode_texts(tokenizer, splits["test"]["texts"], splits["test"]["labels"], config["max_length"])

    id2label = {i: name for i, name in enumerate(label_names)}
    label2id = {name: i for i, name in id2label.items()}
    model_kwargs = {
        "num_labels": num_labels,
        "id2label": id2label,
        "label2id": label2id,
        "ignore_mismatched_sizes": True,
    }
    if config.get("use_safetensors"):
        model_kwargs["use_safetensors"] = True
    model = AutoModelForSequenceClassification.from_pretrained(source, **model_kwargs)

    warmup_steps = estimate_warmup_steps(
        len(splits["train"]["labels"]),
        config["batch_size"],
        config.get("grad_accum", 1),
        config["epochs"],
    )
    training_args = make_training_arguments(
        output_dir=str(run_dir),
        logging_dir=str(LOGS_DIR / f"{model_safe_name(model_name)}_{task_name}"),
        do_train=True,
        do_eval=True,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model=config.get("metric_for_best_model", "eval_macro_f1"),
        greater_is_better=True,
        per_device_train_batch_size=config["batch_size"],
        per_device_eval_batch_size=config.get("eval_batch_size", 32),
        gradient_accumulation_steps=config.get("grad_accum", 1),
        learning_rate=config["learning_rate"],
        num_train_epochs=config["epochs"],
        weight_decay=config.get("weight_decay", 0.02),
        warmup_steps=warmup_steps,
        logging_steps=50,
        save_total_limit=1,
        save_only_model=True,
        seed=SEED,
        data_seed=SEED,
        report_to="none",
        fp16=torch.cuda.is_available(),
    )

    class_weights = get_class_weights(splits["train"]["labels"], num_labels) if use_class_weights else None
    trainer = build_weighted_trainer(
        tokenizer,
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=valid_dataset,
        data_collator=data_collator,
        compute_metrics=make_compute_metrics(task_name, label_names),
        class_weights=class_weights,
        label_smoothing=config.get("label_smoothing", 0.0),
        callbacks=[EarlyStoppingCallback(early_stopping_patience=config.get("early_stop", 2))],
    )

    if source != str(run_dir):
        trainer.train()
        trainer.save_model(str(run_dir))
        tokenizer.save_pretrained(str(run_dir))
        cleanup_checkpoints(run_dir)

    valid_metrics = trainer.evaluate(valid_dataset)
    test_metrics = trainer.evaluate(test_dataset)
    print(f"\n{model_name} {task_name} validation metrics")
    print(pd.Series(valid_metrics).filter(like="eval_").round(4).to_string())
    print(f"\n{model_name} {task_name} test metrics")
    print(pd.Series(test_metrics).filter(like="eval_").round(4).to_string())

    del model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return {
        "model_name": model_name,
        "task_name": task_name,
        "run_dir": run_dir,
        "valid_metrics": valid_metrics,
        "test_metrics": test_metrics,
    }

In [9]:
# Full LIAR optimization run. This retrains into optimized_results_simple_liar_novel_v7 and leaves earlier results untouched.
# After one successful full run, set FORCE_RETRAIN=False and RUN_*_TRAINING=False to only re-evaluate.
FORCE_RETRAIN = False
RUN_BINARY_TRAINING = True
BINARY_MODELS = globals().get("BINARY_HIGH_ACCURACY_MODELS", DEFAULT_MODELS)

binary_artifacts = []
if RUN_BINARY_TRAINING:
    for model_name in BINARY_MODELS:
        artifact = train_or_load_transformer(
            model_name=model_name,
            splits=binary_splits,
            task_name="binary",
            label_names=BINARY_LABEL_NAMES,
            force_retrain=FORCE_RETRAIN,
            use_class_weights=True,
        )
        if not artifact.get("skipped"):
            binary_artifacts.append(artifact)

binary_artifacts


# Novel LIAR-only nested-refit models for binary accuracy: train with original valid added to training,
# and use a small inner validation split from original train for early stopping.
RUN_BINARY_REFIT_TRAINING = True
BINARY_REFIT_MODELS = globals().get("BINARY_REFIT_MODELS", ["distilbert-base-uncased", "bert-base-uncased", "roberta-base"])

binary_refit_artifacts = []
if RUN_BINARY_REFIT_TRAINING:
    for model_name in BINARY_REFIT_MODELS:
        artifact = train_or_load_transformer(
            model_name=model_name,
            splits=binary_refit_splits,
            task_name="binary_refit",
            label_names=BINARY_LABEL_NAMES,
            force_retrain=FORCE_RETRAIN,
            use_class_weights=True,
        )
        if not artifact.get("skipped"):
            binary_refit_artifacts.append(artifact)

binary_refit_artifacts

Training distilbert-base-uncased for binary -> C:\Users\Asus\Downloads\Fake news detection\code\optimized_results_simple_liar_novel_v7\distilbert_base_uncased_binary

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|█████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 5882.12it/s]
[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.22it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.08it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.25it/s]

distilbert-base-uncased binary validation metrics
eval_loss               0.4833
eval_accuracy           0.7266
eval_macro_recall       0.7255
eval_weighted_recall    0.7266
eval_macro_f1           0.7257
eval_weighted_f1        0.7263
eval_fake_recall        0.6964
eval_real_recall        0.7545

distilbert-base-uncased binary test metrics
eval_loss               0.5101
eval_accuracy           0.7514
eval_macro_recall       0.7463
eval_weighted_recall    0.7514
eval_macro_f1           0.7466
eval_weighted_f1        0.7512
eval_fake_recall        0.7086
eval_real_recall        0.7840
Training bert-base-uncased for binary -> C:\Users\Asus\Downloads\Fake news detection\code\optimized_results_simple_liar_novel_v7\bert_base_uncased_binary

Loading weights: 100%|█████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 3827.02it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.80it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.07it/s]
[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.00it/s]

bert-base-uncased binary validation metrics
eval_loss               0.4894
eval_accuracy           0.7477
eval_macro_recall       0.7483
eval_weighted_recall    0.7477
eval_macro_f1           0.7476
eval_weighted_f1        0.7478
eval_fake_recall        0.7646
eval_real_recall        0.7320

bert-base-uncased binary test metrics
eval_loss               0.5107
eval_accuracy           0.7443
eval_macro_recall       0.7429
eval_weighted_recall    0.7443
eval_macro_f1           0.7412
eval_weighted_f1        0.7450
eval_fake_recall        0.7320
eval_real_recall        0.7538
Training roberta-base for binary -> C:\Users\Asus\Downloads\Fake news detection\code\optimized_results_simple_liar_novel_v7\roberta_base_binary

Loading weights: 100%|█████████████████████████████████████████████████████████████| 197/197 [00:00<00:00, 5184.33it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.29it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.60it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.66it/s]

roberta-base binary validation metrics
eval_loss               0.4855
eval_accuracy           0.7422
eval_macro_recall       0.7411
eval_weighted_recall    0.7422
eval_macro_f1           0.7414
eval_weighted_f1        0.7420
eval_fake_recall        0.7143
eval_real_recall        0.7680

roberta-base binary test metrics
eval_loss               0.5092
eval_accuracy           0.7521
eval_macro_recall       0.7481
eval_weighted_recall    0.7521
eval_macro_f1           0.7479
eval_weighted_f1        0.7522
eval_fake_recall        0.7176
eval_real_recall        0.7785
Training distilbert-base-uncased for binary_refit -> C:\Users\Asus\Downloads\Fake news detection\code\optimized_results_simple_liar_novel_v7\distilbert_base_uncased_binary_refit

Loading weights: 100%|█████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 5263.21it/s]
[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.12it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.96it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.98it/s]

distilbert-base-uncased binary_refit validation metrics
eval_loss               0.4772
eval_accuracy           0.7591
eval_macro_recall       0.7560
eval_weighted_recall    0.7591
eval_macro_f1           0.7557
eval_weighted_f1        0.7593

distilbert-base-uncased binary_refit test metrics
eval_loss               0.4995
eval_accuracy           0.7521
eval_macro_recall       0.7477
eval_weighted_recall    0.7521
eval_macro_f1           0.7477
eval_weighted_f1        0.7521
Training bert-base-uncased for binary_refit -> C:\Users\Asus\Downloads\Fake news detection\code\optimized_results_simple_liar_novel_v7\bert_base_uncased_binary_refit

Loading weights: 100%|█████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 3491.12it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.04it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.08it/s]
[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.09it/s]

bert-base-uncased binary_refit validation metrics
eval_loss               0.4793
eval_accuracy           0.7579
eval_macro_recall       0.7460
eval_weighted_recall    0.7579
eval_macro_f1           0.7490
eval_weighted_f1        0.7549

bert-base-uncased binary_refit test metrics
eval_loss               0.5079
eval_accuracy           0.7490
eval_macro_recall       0.7379
eval_weighted_recall    0.7490
eval_macro_f1           0.7405
eval_weighted_f1        0.7467
Training roberta-base for binary_refit -> C:\Users\Asus\Downloads\Fake news detection\code\optimized_results_simple_liar_novel_v7\roberta_base_binary_refit

Loading weights: 100%|█████████████████████████████████████████████████████████████| 197/197 [00:00<00:00, 3581.94it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.46it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.60it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.67it/s]

roberta-base binary_refit validation metrics
eval_loss               0.4791
eval_accuracy           0.7640
eval_macro_recall       0.7575
eval_weighted_recall    0.7640
eval_macro_f1           0.7589
eval_weighted_f1        0.7632

roberta-base binary_refit test metrics
eval_loss               0.5064
eval_accuracy           0.7537
eval_macro_recall       0.7469
eval_weighted_recall    0.7537
eval_macro_f1           0.7480
eval_weighted_f1        0.7531

[{'model_name': 'distilbert-base-uncased',
  'task_name': 'binary_refit',
  'run_dir': WindowsPath('C:/Users/Asus/Downloads/Fake news detection/code/optimized_results_simple_liar_novel_v7/distilbert_base_uncased_binary_refit'),
  'valid_metrics': {'eval_loss': 0.47715869545936584,
   'eval_accuracy': 0.7591240875912408,
   'eval_macro_recall': 0.7559704184704185,
   'eval_weighted_recall': 0.7591240875912408,
   'eval_macro_f1': 0.7556509728561134,
   'eval_weighted_f1': 0.7592658473763481},
  'test_metrics': {'eval_loss': 0.4995276927947998,
   'eval_accuracy': 0.7521434138737334,
   'eval_macro_recall': 0.7476608809238716,
   'eval_weighted_recall': 0.7521434138737334,
   'eval_macro_f1': 0.7476608809238716,
   'eval_weighted_f1': 0.7521434138737334}},
 {'model_name': 'bert-base-uncased',
  'task_name': 'binary_refit',
  'run_dir': WindowsPath('C:/Users/Asus/Downloads/Fake news detection/code/optimized_results_simple_liar_novel_v7/bert_base_uncased_binary_refit'),
  'valid_metrics': {'eval_loss': 0.47926098108291626,
   'eval_accuracy': 0.7579075425790754,
   'eval_macro_recall': 0.745995670995671,
   'eval_weighted_recall': 0.7579075425790754,
   'eval_macro_f1': 0.748982213089975,
   'eval_weighted_f1': 0.754855655721512},
  'test_metrics': {'eval_loss': 0.5079458951950073,
   'eval_accuracy': 0.7490257209664848,
   'eval_macro_recall': 0.7379296012983286,
   'eval_weighted_recall': 0.7490257209664848,
   'eval_macro_f1': 0.7404661389621812,
   'eval_weighted_f1': 0.7467480639524641}},
 {'model_name': 'roberta-base',
  'task_name': 'binary_refit',
  'run_dir': WindowsPath('C:/Users/Asus/Downloads/Fake news detection/code/optimized_results_simple_liar_novel_v7/roberta_base_binary_refit'),
  'valid_metrics': {'eval_loss': 0.47908154129981995,
   'eval_accuracy': 0.7639902676399026,
   'eval_macro_recall': 0.7575396825396825,
   'eval_weighted_recall': 0.7639902676399026,
   'eval_macro_f1': 0.7588509626726188,
   'eval_weighted_f1': 0.7632193718948102},
  'test_metrics': {'eval_loss': 0.5063763856887817,
   'eval_accuracy': 0.7537022603273578,
   'eval_macro_recall': 0.7469211700790674,
   'eval_weighted_recall': 0.7537022603273578,
   'eval_macro_f1': 0.7479998010989284,
   'eval_weighted_f1': 0.7530522390681585}}]

In [10]:
def predict_probabilities(model_dir, texts, num_labels, max_length=128, batch_size=32):
    model_dir = Path(model_dir)
    tokenizer = AutoTokenizer.from_pretrained(str(model_dir), local_files_only=True)
    model = AutoModelForSequenceClassification.from_pretrained(str(model_dir), num_labels=num_labels, local_files_only=True).to(device)
    model.eval()

    if not torch.cuda.is_available():
        batch_size = min(batch_size, 8)

    all_probs = []
    for start in range(0, len(texts), batch_size):
        batch_texts = texts[start:start + batch_size]
        inputs = tokenizer(
            batch_texts,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=max_length,
        ).to(device)
        with torch.inference_mode():
            logits = model(**inputs).logits
            probs = torch.softmax(logits, dim=-1).detach().cpu().numpy()
        all_probs.append(probs)

    result = np.vstack(all_probs)
    del model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    return result


def get_ready_artifacts(task_name, model_names):
    artifacts = []
    for model_name in model_names:
        run_dir = RESULTS_DIR / f"{model_safe_name(model_name)}_{task_name}"
        if local_model_ready(run_dir):
            artifacts.append({"model_name": model_name, "task_name": task_name, "run_dir": run_dir})
        else:
            print(f"Skipping {model_name}; no trained model found at {run_dir}")
    return artifacts


def artifact_probability_key(artifact):
    task_name = artifact.get("task_name", "model")
    return f"{artifact['model_name']} [{task_name}]"


def collect_probabilities(artifacts, splits, num_labels, max_length=128):
    valid_probs = {}
    test_probs = {}
    for artifact in artifacts:
        model_name = artifact["model_name"]
        name = artifact_probability_key(artifact)
        cfg = MODEL_CONFIGS.get(model_name, {})
        model_max_length = cfg.get("max_length", max_length)
        model_batch_size = cfg.get("eval_batch_size", 32)
        print(f"Predicting probabilities: {name} (max_length={model_max_length}, batch_size={model_batch_size})")
        valid_probs[name] = predict_probabilities(artifact["run_dir"], splits["valid"]["texts"], num_labels, max_length=model_max_length, batch_size=model_batch_size)
        test_probs[name] = predict_probabilities(artifact["run_dir"], splits["test"]["texts"], num_labels, max_length=model_max_length, batch_size=model_batch_size)
    return valid_probs, test_probs


def collect_probabilities_for_texts(artifacts, texts, num_labels, split_name="all", max_length=128):
    prob_dict = {}
    for artifact in artifacts:
        model_name = artifact["model_name"]
        name = artifact_probability_key(artifact)
        cfg = MODEL_CONFIGS.get(model_name, {})
        model_max_length = cfg.get("max_length", max_length)
        model_batch_size = cfg.get("eval_batch_size", 32)
        print(f"Predicting {split_name} probabilities: {name} (max_length={model_max_length}, batch_size={model_batch_size})")
        prob_dict[name] = predict_probabilities(
            artifact["run_dir"],
            texts,
            num_labels,
            max_length=model_max_length,
            batch_size=model_batch_size,
        )
    return prob_dict


def average_probabilities(prob_dict, model_names=None, weights=None):
    if not prob_dict:
        return None
    if model_names is None:
        model_names = sorted(prob_dict)
    arrays = [prob_dict[name] for name in model_names]
    if weights is None:
        return np.mean(arrays, axis=0)
    weight_array = np.asarray([weights.get(name, 1.0) for name in model_names], dtype=float)
    if not np.isfinite(weight_array).all() or weight_array.sum() <= 0:
        weight_array = np.ones(len(model_names), dtype=float)
    weight_array = weight_array / weight_array.sum()
    return np.tensordot(weight_array, np.stack(arrays, axis=0), axes=(0, 0))


def majority_vote(prob_dict):
    model_names = sorted(prob_dict)
    model_preds = np.vstack([prob_dict[name].argmax(axis=1) for name in model_names]).T
    avg_probs = average_probabilities(prob_dict, model_names)
    final = []
    for row_idx, row in enumerate(model_preds):
        values, counts = np.unique(row, return_counts=True)
        winners = values[counts == counts.max()]
        if len(winners) == 1:
            final.append(int(winners[0]))
        else:
            final.append(int(winners[np.argmax(avg_probs[row_idx, winners])]))
    return np.asarray(final)


def summed_probability_vote(prob_dict):
    avg_probs = average_probabilities(prob_dict)
    return avg_probs.argmax(axis=1), avg_probs


def subset_probability_vote(prob_dict, model_names):
    avg_probs = average_probabilities(prob_dict, list(model_names))
    return avg_probs.argmax(axis=1), avg_probs


def validation_weighted_probability_vote(valid_prob_dict, test_prob_dict, y_valid, task_name):
    weights = {}
    for name in sorted(valid_prob_dict):
        valid_preds = valid_prob_dict[name].argmax(axis=1)
        weights[name] = f1_score(y_valid, valid_preds, average="macro", zero_division=0)
    test_avg = average_probabilities(test_prob_dict, sorted(test_prob_dict), weights)
    return test_avg.argmax(axis=1), test_avg, weights


def select_best_subset_ensemble(valid_prob_dict, test_prob_dict, y_valid, label_names, task_name, primary_metric="macro_f1"):
    import itertools
    rows = []
    names = sorted(valid_prob_dict)
    for size in range(1, len(names) + 1):
        for subset in itertools.combinations(names, size):
            valid_preds, _ = subset_probability_vote(valid_prob_dict, subset)
            summary = summarize_predictions(y_valid, valid_preds, label_names, task_name)
            rows.append({
                "models": subset,
                "model_count": size,
                **summary,
            })
    table = pd.DataFrame(rows)
    best = table.sort_values([primary_metric, "accuracy", "macro_recall"], ascending=False).iloc[0]
    best_models = tuple(best["models"])
    test_preds, test_probs = subset_probability_vote(test_prob_dict, best_models)
    return best_models, test_preds, test_probs, table


def evaluate_ensembles(valid_prob_dict, test_prob_dict, y_valid, y_test, label_names, task_name, split_name="test"):
    results = {}
    if not test_prob_dict:
        print(f"No probabilities available for {task_name} {split_name}.")
        return results

    majority_preds = majority_vote(test_prob_dict)
    results["majority_vote"] = {
        "preds": majority_preds,
        "summary": print_report(f"{task_name} {split_name} - Majority vote", y_test, majority_preds, label_names, task_name),
    }

    summed_preds, averaged_probs = summed_probability_vote(test_prob_dict)
    results["highest_sum"] = {
        "preds": summed_preds,
        "probs": averaged_probs,
        "summary": print_report(f"{task_name} {split_name} - Highest-sum / averaged probabilities", y_test, summed_preds, label_names, task_name),
    }

    weighted_preds, weighted_probs, model_weights = validation_weighted_probability_vote(valid_prob_dict, test_prob_dict, y_valid, task_name)
    results["validation_weighted"] = {
        "preds": weighted_preds,
        "probs": weighted_probs,
        "weights": model_weights,
        "summary": print_report(f"{task_name} {split_name} - Validation-weighted probability ensemble", y_test, weighted_preds, label_names, task_name),
    }

    selected_models, selected_preds, selected_probs, subset_table = select_best_subset_ensemble(
        valid_prob_dict,
        test_prob_dict,
        y_valid,
        label_names,
        task_name,
        primary_metric="macro_f1",
    )
    results["validation_selected_avg"] = {
        "models": selected_models,
        "preds": selected_preds,
        "probs": selected_probs,
        "subset_table": subset_table,
        "summary": print_report(
            f"{task_name} {split_name} - Validation-selected averaged probabilities {selected_models}",
            y_test,
            selected_preds,
            label_names,
            task_name,
        ),
    }

    return results


def tune_binary_threshold(fake_probs, y_true, optimize_for="accuracy", min_fake_recall=None):
    rows = []
    for threshold in np.linspace(0.05, 0.95, 181):
        preds = np.where(fake_probs >= threshold, 0, 1)
        rows.append({
            "threshold": float(threshold),
            "accuracy": accuracy_score(y_true, preds),
            "fake_recall": recall_score(y_true, preds, pos_label=0, zero_division=0),
            "real_recall": recall_score(y_true, preds, pos_label=1, zero_division=0),
            "macro_recall": recall_score(y_true, preds, average="macro", zero_division=0),
            "macro_f1": f1_score(y_true, preds, average="macro", zero_division=0),
        })
    table = pd.DataFrame(rows)
    candidates = table
    if min_fake_recall is not None:
        eligible = table[table["fake_recall"] >= min_fake_recall]
        if len(eligible):
            candidates = eligible
    best = candidates.sort_values([optimize_for, "macro_f1", "macro_recall", "accuracy"], ascending=False).iloc[0]
    return best, table


def numeric_feature_matrix(frame):
    count_cols = [
        "Barely True Counts",
        "False Counts",
        "Half True Counts",
        "Mostly True Counts",
        "Pants on Fire Counts",
    ]
    counts = frame[count_cols].fillna(0).astype(float).to_numpy()
    total = counts.sum(axis=1, keepdims=True)
    ratios = counts / np.maximum(total, 1.0)
    fake_ratio = counts[:, [0, 1, 4]].sum(axis=1, keepdims=True) / np.maximum(total, 1.0)
    real_ratio = counts[:, [2, 3]].sum(axis=1, keepdims=True) / np.maximum(total, 1.0)
    credibility_margin = real_ratio - fake_ratio
    text_len = frame["text_length"].fillna(0).astype(float).to_numpy().reshape(-1, 1)
    subject_count = frame["Subject"].fillna("").astype(str).str.split(",").str.len().to_numpy(dtype=float).reshape(-1, 1)
    return np.hstack([counts, ratios, total, fake_ratio, real_ratio, credibility_margin, text_len, subject_count])


def probability_features(prob_dict):
    if not prob_dict:
        return None
    ordered = [prob_dict[name] for name in sorted(prob_dict)]
    _, avg_probs = summed_probability_vote(prob_dict)
    return np.hstack(ordered + [avg_probs])


CREDIBILITY_COLUMNS = ["Speaker", "Subject", "Party", "State", "Context", "Job Title"]


def fit_smoothed_target_encoding(frame, labels, num_labels, columns=CREDIBILITY_COLUMNS, alpha=50.0):
    labels = np.asarray(labels, dtype=int)
    prior = np.bincount(labels, minlength=num_labels).astype(float)
    prior = prior / np.maximum(prior.sum(), 1.0)
    encoders = {}
    for column in columns:
        keys = frame[column].fillna("").astype(str).map(clean_field)
        table = {}
        for key, label in zip(keys, labels):
            bucket = table.setdefault(key, np.zeros(num_labels, dtype=float))
            bucket[label] += 1.0
        encoders[column] = {
            key: (counts + alpha * prior) / (counts.sum() + alpha)
            for key, counts in table.items()
        }
    return {"prior": prior, "encoders": encoders, "columns": list(columns)}


def transform_smoothed_target_encoding(frame, fitted):
    prior = fitted["prior"]
    parts = []
    for column in fitted["columns"]:
        mapping = fitted["encoders"][column]
        keys = frame[column].fillna("").astype(str).map(clean_field)
        encoded = np.vstack([mapping.get(key, prior) for key in keys])
        parts.append(encoded)
    return np.hstack(parts)


def credibility_feature_matrix(frame, fitted=None):
    parts = [numeric_feature_matrix(frame)]
    if fitted is not None:
        parts.append(transform_smoothed_target_encoding(frame, fitted))
    return np.hstack(parts)


def credibility_probability_baseline(splits, label_names, task_name):
    num_labels = len(label_names)
    fitted = fit_smoothed_target_encoding(
        splits["train"]["frame"],
        splits["train"]["labels"],
        num_labels,
    )
    x_train = credibility_feature_matrix(splits["train"]["frame"], fitted)
    x_valid = credibility_feature_matrix(splits["valid"]["frame"], fitted)
    x_test = credibility_feature_matrix(splits["test"]["frame"], fitted)

    scaler = StandardScaler()
    x_train = scaler.fit_transform(x_train)
    x_valid = scaler.transform(x_valid)
    x_test = scaler.transform(x_test)

    clf = LogisticRegression(
        max_iter=5000,
        class_weight="balanced",
        C=2.0,
        solver="lbfgs",
        random_state=SEED,
    )
    clf.fit(x_train, splits["train"]["labels"])
    valid_probs = clf.predict_proba(x_valid)
    test_probs = clf.predict_proba(x_test)

    print_report(
        f"{task_name} valid - LIAR credibility baseline",
        splits["valid"]["labels"],
        valid_probs.argmax(axis=1),
        label_names,
        task_name,
    )
    test_summary = print_report(
        f"{task_name} test - LIAR credibility baseline",
        splits["test"]["labels"],
        test_probs.argmax(axis=1),
        label_names,
        task_name,
    )
    return valid_probs, test_probs, test_summary


def tfidf_probability_baseline(splits, label_names, task_name):
    tfidf = FeatureUnion([
        ("word", TfidfVectorizer(max_features=90000, ngram_range=(1, 2), min_df=2, sublinear_tf=True)),
        ("char", TfidfVectorizer(max_features=40000, analyzer="char_wb", ngram_range=(3, 5), min_df=2, sublinear_tf=True)),
    ])
    clf = LogisticRegression(
        max_iter=3000,
        class_weight="balanced",
        C=2.0,
        solver="saga",
        n_jobs=-1,
        random_state=SEED,
    )
    x_train = tfidf.fit_transform(splits["train"]["texts"])
    clf.fit(x_train, splits["train"]["labels"])

    valid_probs = clf.predict_proba(tfidf.transform(splits["valid"]["texts"]))
    test_probs = clf.predict_proba(tfidf.transform(splits["test"]["texts"]))

    print_report(
        f"{task_name} valid - TF-IDF LogisticRegression baseline",
        splits["valid"]["labels"],
        valid_probs.argmax(axis=1),
        label_names,
        task_name,
    )
    test_summary = print_report(
        f"{task_name} test - TF-IDF LogisticRegression baseline",
        splits["test"]["labels"],
        test_probs.argmax(axis=1),
        label_names,
        task_name,
    )
    return valid_probs, test_probs, test_summary


def stacked_meta_ensemble(task_name, splits, valid_prob_dict, test_prob_dict, label_names):
    tfidf_valid_probs, tfidf_test_probs, tfidf_summary = tfidf_probability_baseline(splits, label_names, task_name)
    credibility_valid_probs, credibility_test_probs, credibility_summary = credibility_probability_baseline(splits, label_names, task_name)

    valid_transformer_features = probability_features(valid_prob_dict)
    test_transformer_features = probability_features(test_prob_dict)
    valid_parts = [tfidf_valid_probs, credibility_valid_probs]
    test_parts = [tfidf_test_probs, credibility_test_probs]

    if valid_transformer_features is not None:
        valid_parts.insert(0, valid_transformer_features)
        test_parts.insert(0, test_transformer_features)

    scaler = StandardScaler()
    scaler.fit(numeric_feature_matrix(splits["train"]["frame"]))
    valid_parts.append(scaler.transform(numeric_feature_matrix(splits["valid"]["frame"])))
    test_parts.append(scaler.transform(numeric_feature_matrix(splits["test"]["frame"])))

    x_meta_valid = np.hstack(valid_parts)
    x_meta_test = np.hstack(test_parts)
    y_valid = splits["valid"]["labels"]
    y_test = splits["test"]["labels"]

    meta = LogisticRegression(
        max_iter=3000,
        class_weight="balanced",
        C=1.0,
        solver="lbfgs",
        random_state=SEED,
    )
    meta.fit(x_meta_valid, y_valid)
    meta_test_probs = meta.predict_proba(x_meta_test)
    meta_test_preds = meta_test_probs.argmax(axis=1)
    meta_summary = print_report(
        f"{task_name} test - Stacked meta ensemble",
        y_test,
        meta_test_preds,
        label_names,
        task_name,
    )

    return {
        "tfidf_summary": tfidf_summary,
        "tfidf_test_probs": tfidf_test_probs,
        "tfidf_test_preds": tfidf_test_probs.argmax(axis=1),
        "credibility_summary": credibility_summary,
        "credibility_test_probs": credibility_test_probs,
        "credibility_test_preds": credibility_test_probs.argmax(axis=1),
        "meta_summary": meta_summary,
        "meta_test_probs": meta_test_probs,
        "meta_test_preds": meta_test_preds,
    }


# ===== LIAR-only metadata graph neural network =====
GRAPH_METADATA_COLUMNS = ["Speaker", "Subject", "Party", "State", "Context", "Job Title"]


def metadata_tokens(value, column_name):
    text = clean_field(value).lower()
    if not text:
        return [f"{column_name}:__missing__"]
    if column_name == "Subject":
        pieces = re.split(r"[,;/|]", text)
    else:
        pieces = [text]
    tokens = [piece.strip() for piece in pieces if piece.strip()]
    if not tokens:
        tokens = ["__missing__"]
    return [f"{column_name}:{token}" for token in tokens]


class SimpleGCN(torch.nn.Module):
    def __init__(self, in_dim, hidden_dim, out_dim, dropout=0.25):
        super().__init__()
        self.fc1 = torch.nn.Linear(in_dim, hidden_dim)
        self.fc2 = torch.nn.Linear(hidden_dim, out_dim)
        self.dropout = torch.nn.Dropout(dropout)

    def forward(self, features, adjacency):
        x = torch.sparse.mm(adjacency, features)
        x = self.fc1(x)
        x = torch.relu(x)
        x = self.dropout(x)
        x = torch.sparse.mm(adjacency, x)
        return self.fc2(x)


def build_liar_metadata_graph(splits, num_labels):
    split_order = ["train", "valid", "test"]
    frames = [splits[name]["frame"].reset_index(drop=True) for name in split_order]
    labels = {name: splits[name]["labels"] for name in split_order}
    claim_offsets = {}
    node_count = 0
    for name, frame in zip(split_order, frames):
        claim_offsets[name] = node_count
        node_count += len(frame)

    token_to_id = {}
    edges = []
    token_type = {}
    for split_name, frame in zip(split_order, frames):
        offset = claim_offsets[split_name]
        for row_idx, row in frame.iterrows():
            claim_node = offset + row_idx
            for col_idx, column in enumerate(GRAPH_METADATA_COLUMNS):
                for token in metadata_tokens(row.get(column, ""), column):
                    if token not in token_to_id:
                        token_to_id[token] = node_count
                        token_type[token] = col_idx
                        node_count += 1
                    meta_node = token_to_id[token]
                    edges.append((claim_node, meta_node))
                    edges.append((meta_node, claim_node))

    # Self-loops.
    edges.extend((idx, idx) for idx in range(node_count))
    edge_index = torch.tensor(edges, dtype=torch.long).t().contiguous()

    values = torch.ones(edge_index.shape[1], dtype=torch.float32)
    degree = torch.zeros(node_count, dtype=torch.float32)
    degree.scatter_add_(0, edge_index[0], values)
    norm_values = values / torch.sqrt(degree[edge_index[0]].clamp_min(1.0) * degree[edge_index[1]].clamp_min(1.0))
    adjacency = torch.sparse_coo_tensor(edge_index, norm_values, (node_count, node_count)).coalesce()

    numeric_scaler = StandardScaler()
    numeric_scaler.fit(numeric_feature_matrix(splits["train"]["frame"]))
    numeric_dim = numeric_feature_matrix(splits["train"]["frame"]).shape[1]
    type_dim = 1 + len(GRAPH_METADATA_COLUMNS)
    features = np.zeros((node_count, numeric_dim + type_dim), dtype=np.float32)

    for split_name, frame in zip(split_order, frames):
        offset = claim_offsets[split_name]
        numeric = numeric_scaler.transform(numeric_feature_matrix(frame)).astype(np.float32)
        features[offset:offset + len(frame), :numeric_dim] = numeric
        features[offset:offset + len(frame), numeric_dim] = 1.0  # claim node type

    for token, node_id in token_to_id.items():
        features[node_id, numeric_dim + 1 + token_type[token]] = 1.0

    idx = {
        "train": np.arange(claim_offsets["train"], claim_offsets["train"] + len(frames[0])),
        "valid": np.arange(claim_offsets["valid"], claim_offsets["valid"] + len(frames[1])),
        "test": np.arange(claim_offsets["test"], claim_offsets["test"] + len(frames[2])),
    }
    return features, adjacency, idx, labels


def liar_metadata_gnn_baseline(task_name, splits, label_names, epochs=220, hidden_dim=128, patience=25):
    num_labels = len(label_names)
    features_np, adjacency_cpu, idx_np, labels_np = build_liar_metadata_graph(splits, num_labels)
    graph_device = device if torch.cuda.is_available() else torch.device("cpu")
    features = torch.tensor(features_np, dtype=torch.float32, device=graph_device)
    adjacency = adjacency_cpu.to(graph_device)
    train_idx = torch.tensor(idx_np["train"], dtype=torch.long, device=graph_device)
    valid_idx = torch.tensor(idx_np["valid"], dtype=torch.long, device=graph_device)
    test_idx = torch.tensor(idx_np["test"], dtype=torch.long, device=graph_device)
    y_train = torch.tensor(labels_np["train"], dtype=torch.long, device=graph_device)
    y_valid = torch.tensor(labels_np["valid"], dtype=torch.long, device=graph_device)

    model = SimpleGCN(features.shape[1], hidden_dim, num_labels, dropout=0.30).to(graph_device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=0.01, weight_decay=5e-4)
    weights = get_class_weights(labels_np["train"], num_labels).to(graph_device)
    loss_fn = torch.nn.CrossEntropyLoss(weight=weights)

    best_state = None
    best_score = -1.0
    bad_epochs = 0
    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()
        logits = model(features, adjacency)
        loss = loss_fn(logits[train_idx], y_train)
        loss.backward()
        optimizer.step()

        model.eval()
        with torch.no_grad():
            logits = model(features, adjacency)
            valid_preds = logits[valid_idx].argmax(dim=1).detach().cpu().numpy()
        valid_score = f1_score(labels_np["valid"], valid_preds, average="macro", zero_division=0)
        if valid_score > best_score:
            best_score = valid_score
            best_state = {key: value.detach().cpu().clone() for key, value in model.state_dict().items()}
            bad_epochs = 0
        else:
            bad_epochs += 1
        if bad_epochs >= patience:
            break

    if best_state is not None:
        model.load_state_dict({key: value.to(graph_device) for key, value in best_state.items()})
    model.eval()
    with torch.no_grad():
        logits = model(features, adjacency)
        probs = torch.softmax(logits, dim=1).detach().cpu().numpy()

    valid_probs = probs[idx_np["valid"]]
    test_probs = probs[idx_np["test"]]
    valid_summary = print_report(
        f"{task_name} valid - LIAR metadata GNN",
        labels_np["valid"],
        valid_probs.argmax(axis=1),
        label_names,
        task_name,
    )
    test_summary = print_report(
        f"{task_name} test - LIAR metadata GNN",
        labels_np["test"],
        test_probs.argmax(axis=1),
        label_names,
        task_name,
    )
    return {
        "valid_probs": valid_probs,
        "test_probs": test_probs,
        "valid_summary": valid_summary,
        "test_summary": test_summary,
        "test_preds": test_probs.argmax(axis=1),
    }


def tune_gnn_transformer_blend(task_name, y_valid, y_test, transformer_valid_probs, transformer_test_probs, gnn_valid_probs, gnn_test_probs, label_names):
    rows = []
    for alpha in np.linspace(0.0, 1.0, 51):
        valid_probs = alpha * transformer_valid_probs + (1.0 - alpha) * gnn_valid_probs
        valid_preds = valid_probs.argmax(axis=1)
        rows.append({"alpha_transformer": float(alpha), **summarize_predictions(y_valid, valid_preds, label_names, task_name)})
    table = pd.DataFrame(rows)
    best = table.sort_values(["accuracy", "macro_f1", "macro_recall"], ascending=False).iloc[0]
    test_probs = best["alpha_transformer"] * transformer_test_probs + (1.0 - best["alpha_transformer"]) * gnn_test_probs
    test_preds = test_probs.argmax(axis=1)
    summary = print_report(
        f"{task_name} test - Transformer + LIAR metadata GNN blend",
        y_test,
        test_preds,
        label_names,
        task_name,
    )
    print("Best GNN blend alpha on validation:", round(float(best["alpha_transformer"]), 4))
    return {"best": best, "table": table, "test_probs": test_probs, "test_preds": test_preds, "summary": summary}

In [11]:
# Binary ensemble evaluation and threshold tuning.
binary_ready_artifacts = get_ready_artifacts("binary", BINARY_MODELS)
binary_refit_ready_artifacts = get_ready_artifacts("binary_refit", BINARY_REFIT_MODELS)
binary_all_ready_artifacts = binary_ready_artifacts + binary_refit_ready_artifacts
binary_valid_probs, binary_test_probs = collect_probabilities(
    binary_all_ready_artifacts,
    binary_splits,
    num_labels=len(BINARY_LABEL_NAMES),
    max_length=160,
)

y_valid_binary = binary_splits["valid"]["labels"]
y_test_binary = binary_splits["test"]["labels"]

binary_test_ensemble = evaluate_ensembles(
    binary_valid_probs,
    binary_test_probs,
    y_valid_binary,
    y_test_binary,
    BINARY_LABEL_NAMES,
    "binary",
    "test",
)

if binary_valid_probs:
    selected_valid_models = binary_test_ensemble.get("validation_selected_avg", {}).get("models", tuple(sorted(binary_valid_probs)))
    _, valid_selected_probs = subset_probability_vote(binary_valid_probs, selected_valid_models)
    _, test_selected_probs = subset_probability_vote(binary_test_probs, selected_valid_models)

    best_accuracy_threshold, threshold_table = tune_binary_threshold(
        valid_selected_probs[:, 0],
        y_valid_binary,
        optimize_for="accuracy",
    )
    print("\nBest validation threshold for binary accuracy")
    print(best_accuracy_threshold.round(4).to_string())

    threshold_preds_test = np.where(test_selected_probs[:, 0] >= best_accuracy_threshold["threshold"], 0, 1)
    threshold_test_summary = print_report(
        "binary test - Validation-selected ensemble + tuned accuracy threshold",
        y_test_binary,
        threshold_preds_test,
        BINARY_LABEL_NAMES,
        "binary",
    )

binary_stacked_results = stacked_meta_ensemble(
    "binary",
    binary_splits,
    binary_valid_probs,
    binary_test_probs,
    BINARY_LABEL_NAMES,
)

binary_gnn_results = liar_metadata_gnn_baseline("binary", binary_splits, BINARY_LABEL_NAMES)

if binary_valid_probs:
    _, binary_transformer_valid_avg = summed_probability_vote(binary_valid_probs)
    _, binary_transformer_test_avg = summed_probability_vote(binary_test_probs)
    binary_gnn_blend_results = tune_gnn_transformer_blend(
        "binary",
        y_valid_binary,
        y_test_binary,
        binary_transformer_valid_avg,
        binary_transformer_test_avg,
        binary_gnn_results["valid_probs"],
        binary_gnn_results["test_probs"],
        BINARY_LABEL_NAMES,
    )

binary_predictions_for_report = {}
for model_name, probs in sorted(binary_test_probs.items()):
    binary_predictions_for_report[f"Individual: {model_name}"] = probs.argmax(axis=1)
for key, label in [
    ("majority_vote", "Ensemble: majority vote"),
    ("highest_sum", "Ensemble: highest-sum / avg prob"),
    ("validation_weighted", "Ensemble: validation-weighted avg prob"),
    ("validation_selected_avg", "Ensemble: validation-selected avg prob"),
]:
    if key in binary_test_ensemble:
        binary_predictions_for_report[label] = binary_test_ensemble[key]["preds"]
if "threshold_preds_test" in globals():
    binary_predictions_for_report["Ensemble: validation-selected + tuned threshold"] = threshold_preds_test
if "binary_gnn_results" in globals():
    binary_predictions_for_report["GNN: LIAR metadata graph"] = binary_gnn_results["test_preds"]
if "binary_gnn_blend_results" in globals():
    binary_predictions_for_report["Ensemble: transformer + LIAR metadata GNN"] = binary_gnn_blend_results["test_preds"]
if isinstance(binary_stacked_results, dict):
    if "tfidf_summary" in binary_stacked_results:
        binary_predictions_for_report["Baseline: TF-IDF + metadata"] = binary_stacked_results.get("tfidf_test_preds", np.array([]))
    if "credibility_test_preds" in binary_stacked_results:
        binary_predictions_for_report["Baseline: LIAR credibility"] = binary_stacked_results["credibility_test_preds"]
    if "meta_test_preds" in binary_stacked_results:
        binary_predictions_for_report["Ensemble: stacked transformer + credibility meta"] = binary_stacked_results["meta_test_preds"]

# Fix baseline predictions for report if the summary-only branch above was created.
if "Baseline: TF-IDF + metadata" in binary_predictions_for_report and len(binary_predictions_for_report["Baseline: TF-IDF + metadata"]) == 0:
    binary_predictions_for_report.pop("Baseline: TF-IDF + metadata")

Predicting probabilities: distilbert-base-uncased [binary] (max_length=128, batch_size=32)

Loading weights: 100%|█████████████████████████████████████████████████████████████| 104/104 [00:00<00:00, 4521.74it/s]
Loading weights: 100%|█████████████████████████████████████████████████████████████| 104/104 [00:00<00:00, 4959.22it/s]

Predicting probabilities: bert-base-uncased [binary] (max_length=128, batch_size=32)

Loading weights: 100%|█████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 4467.23it/s]
Loading weights: 100%|█████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 5025.06it/s]

Predicting probabilities: roberta-base [binary] (max_length=128, batch_size=32)

Loading weights: 100%|█████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 4785.84it/s]
Loading weights: 100%|█████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 4786.79it/s]

Predicting probabilities: distilbert-base-uncased [binary_refit] (max_length=128, batch_size=32)

Loading weights: 100%|█████████████████████████████████████████████████████████████| 104/104 [00:00<00:00, 4952.29it/s]
Loading weights: 100%|█████████████████████████████████████████████████████████████| 104/104 [00:00<00:00, 5475.52it/s]

Predicting probabilities: bert-base-uncased [binary_refit] (max_length=128, batch_size=32)

Loading weights: 100%|█████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 4681.30it/s]
Loading weights: 100%|█████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 4568.12it/s]

Predicting probabilities: roberta-base [binary_refit] (max_length=128, batch_size=32)

Loading weights: 100%|█████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 5025.39it/s]
Loading weights: 100%|█████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 4466.90it/s]

binary test - Majority vote
accuracy           0.7607
macro_recall       0.7542
weighted_recall    0.7607
macro_f1           0.7552
weighted_f1        0.7601
fake_recall        0.7050
real_recall        0.8033
              precision    recall  f1-score   support

        fake       0.73      0.71      0.72       556
        real       0.78      0.80      0.79       727

    accuracy                           0.76      1283
   macro avg       0.76      0.75      0.76      1283
weighted avg       0.76      0.76      0.76      1283


binary test - Highest-sum / averaged probabilities
accuracy           0.7607
macro_recall       0.7542
weighted_recall    0.7607
macro_f1           0.7552
weighted_f1        0.7601
fake_recall        0.7050
real_recall        0.8033
              precision    recall  f1-score   support

        fake       0.73      0.71      0.72       556
        real       0.78      0.80      0.79       727

    accuracy                           0.76      1283
   macro avg       0.76      0.75      0.76      1283
weighted avg       0.76      0.76      0.76      1283


binary test - Validation-weighted probability ensemble
accuracy           0.7599
macro_recall       0.7535
weighted_recall    0.7599
macro_f1           0.7545
weighted_f1        0.7594
fake_recall        0.7050
real_recall        0.8019
              precision    recall  f1-score   support

        fake       0.73      0.71      0.72       556
        real       0.78      0.80      0.79       727

    accuracy                           0.76      1283
   macro avg       0.76      0.75      0.75      1283
weighted avg       0.76      0.76      0.76      1283


binary test - Validation-selected averaged probabilities ('bert-base-uncased [binary_refit]', 'distilbert-base-uncased [binary_refit]', 'roberta-base [binary_refit]')
accuracy           0.7646
macro_recall       0.7568
weighted_recall    0.7646
macro_f1           0.7584
weighted_f1        0.7636
fake_recall        0.6978
real_recall        0.8157
              precision    recall  f1-score   support

        fake       0.74      0.70      0.72       556
        real       0.78      0.82      0.80       727

    accuracy                           0.76      1283
   macro avg       0.76      0.76      0.76      1283
weighted avg       0.76      0.76      0.76      1283


Best validation threshold for binary accuracy
threshold       0.5000
accuracy        0.8076
fake_recall     0.7597
real_recall     0.8518
macro_recall    0.8058
macro_f1        0.8064

binary test - Validation-selected ensemble + tuned accuracy threshold
accuracy           0.7646
macro_recall       0.7568
weighted_recall    0.7646
macro_f1           0.7584
weighted_f1        0.7636
fake_recall        0.6978
real_recall        0.8157
              precision    recall  f1-score   support

        fake       0.74      0.70      0.72       556
        real       0.78      0.82      0.80       727

    accuracy                           0.76      1283
   macro avg       0.76      0.76      0.76      1283
weighted avg       0.76      0.76      0.76      1283


binary valid - TF-IDF LogisticRegression baseline
accuracy           0.6690
macro_recall       0.6679
weighted_recall    0.6690
macro_f1           0.6680
weighted_f1        0.6688
fake_recall        0.6412
real_recall        0.6946
              precision    recall  f1-score   support

        fake       0.66      0.64      0.65       616
        real       0.68      0.69      0.69       668

    accuracy                           0.67      1284
   macro avg       0.67      0.67      0.67      1284
weighted avg       0.67      0.67      0.67      1284


binary test - TF-IDF LogisticRegression baseline
accuracy           0.6617
macro_recall       0.6541
weighted_recall    0.6617
macro_f1           0.6545
weighted_f1        0.6612
fake_recall        0.5971
real_recall        0.7111
              precision    recall  f1-score   support

        fake       0.61      0.60      0.60       556
        real       0.70      0.71      0.70       727

    accuracy                           0.66      1283
   macro avg       0.66      0.65      0.65      1283
weighted avg       0.66      0.66      0.66      1283


binary valid - LIAR credibility baseline
accuracy           0.7259
macro_recall       0.7251
weighted_recall    0.7259
macro_f1           0.7252
weighted_f1        0.7258
fake_recall        0.7062
real_recall        0.7440
              precision    recall  f1-score   support

        fake       0.72      0.71      0.71       616
        real       0.73      0.74      0.74       668

    accuracy                           0.73      1284
   macro avg       0.73      0.73      0.73      1284
weighted avg       0.73      0.73      0.73      1284


binary test - LIAR credibility baseline
accuracy           0.7295
macro_recall       0.7269
weighted_recall    0.7295
macro_f1           0.7258
weighted_f1        0.7301
fake_recall        0.7068
real_recall        0.7469
              precision    recall  f1-score   support

        fake       0.68      0.71      0.69       556
        real       0.77      0.75      0.76       727

    accuracy                           0.73      1283
   macro avg       0.73      0.73      0.73      1283
weighted avg       0.73      0.73      0.73      1283


binary test - Stacked meta ensemble
accuracy           0.7436
macro_recall       0.7392
weighted_recall    0.7436
macro_f1           0.7391
weighted_f1        0.7436
fake_recall        0.7068
real_recall        0.7717
              precision    recall  f1-score   support

        fake       0.70      0.71      0.70       556
        real       0.77      0.77      0.77       727

    accuracy                           0.74      1283
   macro avg       0.74      0.74      0.74      1283
weighted avg       0.74      0.74      0.74      1283


binary valid - LIAR metadata GNN
accuracy           0.7274
macro_recall       0.7276
weighted_recall    0.7274
macro_f1           0.7272
weighted_f1        0.7275
fake_recall        0.7321
real_recall        0.7231
              precision    recall  f1-score   support

        fake       0.71      0.73      0.72       616
        real       0.75      0.72      0.73       668

    accuracy                           0.73      1284
   macro avg       0.73      0.73      0.73      1284
weighted avg       0.73      0.73      0.73      1284


binary test - LIAR metadata GNN
accuracy           0.7288
macro_recall       0.7291
weighted_recall    0.7288
macro_f1           0.7263
weighted_f1        0.7298
fake_recall        0.7320
real_recall        0.7263
              precision    recall  f1-score   support

        fake       0.67      0.73      0.70       556
        real       0.78      0.73      0.75       727

    accuracy                           0.73      1283
   macro avg       0.73      0.73      0.73      1283
weighted avg       0.73      0.73      0.73      1283


binary test - Transformer + LIAR metadata GNN blend
accuracy           0.7576
macro_recall       0.7516
weighted_recall    0.7576
macro_f1           0.7524
weighted_f1        0.7572
fake_recall        0.7068
real_recall        0.7964
              precision    recall  f1-score   support

        fake       0.73      0.71      0.72       556
        real       0.78      0.80      0.79       727

    accuracy                           0.76      1283
   macro avg       0.75      0.75      0.75      1283
weighted avg       0.76      0.76      0.76      1283

Best GNN blend alpha on validation: 0.94

In [12]:
# Multiclass and hierarchical fine-tuning.
RUN_MULTICLASS_TRAINING = True
MULTICLASS_MODELS = DEFAULT_MODELS

# Lightweight subtype hierarchy is enabled with DistilBERT only for the unattended full run.
RUN_HIERARCHICAL_SUBTYPE_TRAINING = True
HIERARCHICAL_SUBTYPE_MODELS = HIERARCHICAL_MODELS

multiclass_artifacts = []
if RUN_MULTICLASS_TRAINING:
    for model_name in MULTICLASS_MODELS:
        artifact = train_or_load_transformer(
            model_name=model_name,
            splits=multiclass_splits,
            task_name="multiclass",
            label_names=MULTICLASS_LABEL_NAMES,
            force_retrain=FORCE_RETRAIN,
            use_class_weights=True,
        )
        if not artifact.get("skipped"):
            multiclass_artifacts.append(artifact)

fake_subtype_artifacts = []
real_subtype_artifacts = []
if RUN_HIERARCHICAL_SUBTYPE_TRAINING:
    for model_name in HIERARCHICAL_SUBTYPE_MODELS:
        artifact = train_or_load_transformer(
            model_name=model_name,
            splits=fake_subtype_splits,
            task_name="fake_subtype",
            label_names=FAKE_SUBTYPE_LABEL_NAMES,
            force_retrain=FORCE_RETRAIN,
            use_class_weights=True,
        )
        if not artifact.get("skipped"):
            fake_subtype_artifacts.append(artifact)

    for model_name in HIERARCHICAL_SUBTYPE_MODELS:
        artifact = train_or_load_transformer(
            model_name=model_name,
            splits=real_subtype_splits,
            task_name="real_subtype",
            label_names=REAL_SUBTYPE_LABEL_NAMES,
            force_retrain=FORCE_RETRAIN,
            use_class_weights=True,
        )
        if not artifact.get("skipped"):
            real_subtype_artifacts.append(artifact)

multiclass_artifacts, fake_subtype_artifacts, real_subtype_artifacts

Training distilbert-base-uncased for multiclass -> C:\Users\Asus\Downloads\Fake news detection\code\optimized_results_simple_liar_novel_v7\distilbert_base_uncased_multiclass

Loading weights: 100%|█████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 5554.71it/s]
[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.68it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.02it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.91it/s]

distilbert-base-uncased multiclass validation metrics
eval_loss               1.2899
eval_accuracy           0.4688
eval_macro_recall       0.4792
eval_weighted_recall    0.4688
eval_macro_f1           0.4651
eval_weighted_f1        0.4645

distilbert-base-uncased multiclass test metrics
eval_loss               1.3195
eval_accuracy           0.4170
eval_macro_recall       0.4444
eval_weighted_recall    0.4170
eval_macro_f1           0.4194
eval_weighted_f1        0.4116
Training bert-base-uncased for multiclass -> C:\Users\Asus\Downloads\Fake news detection\code\optimized_results_simple_liar_novel_v7\bert_base_uncased_multiclass

Loading weights: 100%|█████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 5528.18it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.95it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.98it/s]
[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.69it/s]

bert-base-uncased multiclass validation metrics
eval_loss               1.2731
eval_accuracy           0.4502
eval_macro_recall       0.4605
eval_weighted_recall    0.4502
eval_macro_f1           0.4478
eval_weighted_f1        0.4490

bert-base-uncased multiclass test metrics
eval_loss               1.2719
eval_accuracy           0.4443
eval_macro_recall       0.4743
eval_weighted_recall    0.4443
eval_macro_f1           0.4499
eval_weighted_f1        0.4398
Training roberta-base for multiclass -> C:\Users\Asus\Downloads\Fake news detection\code\optimized_results_simple_liar_novel_v7\roberta_base_multiclass

Loading weights: 100%|█████████████████████████████████████████████████████████████| 197/197 [00:00<00:00, 5051.18it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.51it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.66it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.70it/s]

roberta-base multiclass validation metrics
eval_loss               1.7927
eval_accuracy           0.1931
eval_macro_recall       0.1667
eval_weighted_recall    0.1931
eval_macro_f1           0.0540
eval_weighted_f1        0.0625

roberta-base multiclass test metrics
eval_loss               1.7904
eval_accuracy           0.2081
eval_macro_recall       0.1667
eval_weighted_recall    0.2081
eval_macro_f1           0.0574
eval_weighted_f1        0.0717
Training distilbert-base-uncased for fake_subtype -> C:\Users\Asus\Downloads\Fake news detection\code\optimized_results_simple_liar_novel_v7\distilbert_base_uncased_fake_subtype

Loading weights: 100%|█████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 5881.95it/s]
[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.13it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.84it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.93it/s]

distilbert-base-uncased fake_subtype validation metrics
eval_loss               0.7507
eval_accuracy           0.6169
eval_macro_recall       0.6359
eval_weighted_recall    0.6169
eval_macro_f1           0.6153
eval_weighted_f1        0.6169

distilbert-base-uncased fake_subtype test metrics
eval_loss               0.7446
eval_accuracy           0.6061
eval_macro_recall       0.6379
eval_weighted_recall    0.6061
eval_macro_f1           0.6029
eval_weighted_f1        0.6075
Training distilbert-base-uncased for real_subtype -> C:\Users\Asus\Downloads\Fake news detection\code\optimized_results_simple_liar_novel_v7\distilbert_base_uncased_real_subtype

Loading weights: 100%|█████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 5883.03it/s]
[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.82it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.05it/s]
Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.96it/s]

distilbert-base-uncased real_subtype validation metrics
eval_loss               0.8435
eval_accuracy           0.5958
eval_macro_recall       0.5731
eval_weighted_recall    0.5958
eval_macro_f1           0.5740
eval_weighted_f1        0.5893

distilbert-base-uncased real_subtype test metrics
eval_loss               0.8679
eval_accuracy           0.5681
eval_macro_recall       0.5588
eval_weighted_recall    0.5681
eval_macro_f1           0.5594
eval_weighted_f1        0.5643

([{'model_name': 'distilbert-base-uncased',
   'task_name': 'multiclass',
   'run_dir': WindowsPath('C:/Users/Asus/Downloads/Fake news detection/code/optimized_results_simple_liar_novel_v7/distilbert_base_uncased_multiclass'),
   'valid_metrics': {'eval_loss': 1.2898681163787842,
    'eval_accuracy': 0.4688473520249221,
    'eval_macro_recall': 0.47918008262680517,
    'eval_weighted_recall': 0.4688473520249221,
    'eval_macro_f1': 0.4651339200748284,
    'eval_weighted_f1': 0.4644888180609851},
   'test_metrics': {'eval_loss': 1.3194626569747925,
    'eval_accuracy': 0.4169914263445051,
    'eval_macro_recall': 0.44442711019793824,
    'eval_weighted_recall': 0.4169914263445051,
    'eval_macro_f1': 0.41939449098595855,
    'eval_weighted_f1': 0.4115745420616898}},
  {'model_name': 'bert-base-uncased',
   'task_name': 'multiclass',
   'run_dir': WindowsPath('C:/Users/Asus/Downloads/Fake news detection/code/optimized_results_simple_liar_novel_v7/bert_base_uncased_multiclass'),
   'valid_metrics': {'eval_loss': 1.273121953010559,
    'eval_accuracy': 0.4501557632398754,
    'eval_macro_recall': 0.4605269166851411,
    'eval_weighted_recall': 0.4501557632398754,
    'eval_macro_f1': 0.44777270310703976,
    'eval_weighted_f1': 0.4489897778700481},
   'test_metrics': {'eval_loss': 1.2719000577926636,
    'eval_accuracy': 0.4442712392829306,
    'eval_macro_recall': 0.47431470785300456,
    'eval_weighted_recall': 0.4442712392829306,
    'eval_macro_f1': 0.44988034057234444,
    'eval_weighted_f1': 0.4397692157054546}},
  {'model_name': 'roberta-base',
   'task_name': 'multiclass',
   'run_dir': WindowsPath('C:/Users/Asus/Downloads/Fake news detection/code/optimized_results_simple_liar_novel_v7/roberta_base_multiclass'),
   'valid_metrics': {'eval_loss': 1.7927277088165283,
    'eval_accuracy': 0.19314641744548286,
    'eval_macro_recall': 0.16666666666666666,
    'eval_weighted_recall': 0.19314641744548286,
    'eval_macro_f1': 0.053959965187119235,
    'eval_weighted_f1': 0.06253304376825033},
   'test_metrics': {'eval_loss': 1.7904036045074463,
    'eval_accuracy': 0.20810600155884645,
    'eval_macro_recall': 0.16666666666666666,
    'eval_weighted_recall': 0.20810600155884645,
    'eval_macro_f1': 0.057419354838709684,
    'eval_weighted_f1': 0.07169587408543485}}],
 [{'model_name': 'distilbert-base-uncased',
   'task_name': 'fake_subtype',
   'run_dir': WindowsPath('C:/Users/Asus/Downloads/Fake news detection/code/optimized_results_simple_liar_novel_v7/distilbert_base_uncased_fake_subtype'),
   'valid_metrics': {'eval_loss': 0.7506529688835144,
    'eval_accuracy': 0.6168831168831169,
    'eval_macro_recall': 0.635927040971661,
    'eval_weighted_recall': 0.6168831168831169,
    'eval_macro_f1': 0.6152596258358852,
    'eval_weighted_f1': 0.6168813577130594},
   'test_metrics': {'eval_loss': 0.7445998191833496,
    'eval_accuracy': 0.6061151079136691,
    'eval_macro_recall': 0.6378848706487877,
    'eval_weighted_recall': 0.6061151079136691,
    'eval_macro_f1': 0.6028703743482224,
    'eval_weighted_f1': 0.6075409841695042}}],
 [{'model_name': 'distilbert-base-uncased',
   'task_name': 'real_subtype',
   'run_dir': WindowsPath('C:/Users/Asus/Downloads/Fake news detection/code/optimized_results_simple_liar_novel_v7/distilbert_base_uncased_real_subtype'),
   'valid_metrics': {'eval_loss': 0.8434547185897827,
    'eval_accuracy': 0.5958083832335329,
    'eval_macro_recall': 0.5731190210209616,
    'eval_weighted_recall': 0.5958083832335329,
    'eval_macro_f1': 0.57402619796048,
    'eval_weighted_f1': 0.5892942568892092},
   'test_metrics': {'eval_loss': 0.8678733110427856,
    'eval_accuracy': 0.5680880330123796,
    'eval_macro_recall': 0.5588124904966263,
    'eval_weighted_recall': 0.5680880330123796,
    'eval_macro_f1': 0.5594238951381808,
    'eval_weighted_f1': 0.5643157050014979}}])

In [13]:
# Multiclass ensemble evaluation.
multiclass_ready_artifacts = get_ready_artifacts("multiclass", MULTICLASS_MODELS)
multiclass_valid_probs, multiclass_test_probs = collect_probabilities(
    multiclass_ready_artifacts,
    multiclass_splits,
    num_labels=len(MULTICLASS_LABEL_NAMES),
    max_length=160,
)

y_valid_multi = multiclass_splits["valid"]["labels"]
y_test_multi = multiclass_splits["test"]["labels"]

multiclass_test_ensemble = evaluate_ensembles(
    multiclass_valid_probs,
    multiclass_test_probs,
    y_valid_multi,
    y_test_multi,
    MULTICLASS_LABEL_NAMES,
    "multiclass",
    "test",
)

multiclass_stacked_results = stacked_meta_ensemble(
    "multiclass",
    multiclass_splits,
    multiclass_valid_probs,
    multiclass_test_probs,
    MULTICLASS_LABEL_NAMES,
)


multiclass_gnn_results = liar_metadata_gnn_baseline("multiclass", multiclass_splits, MULTICLASS_LABEL_NAMES)

if multiclass_valid_probs:
    _, multiclass_transformer_valid_avg = summed_probability_vote(multiclass_valid_probs)
    _, multiclass_transformer_test_avg = summed_probability_vote(multiclass_test_probs)
    multiclass_gnn_blend_results = tune_gnn_transformer_blend(
        "multiclass",
        y_valid_multi,
        y_test_multi,
        multiclass_transformer_valid_avg,
        multiclass_transformer_test_avg,
        multiclass_gnn_results["valid_probs"],
        multiclass_gnn_results["test_probs"],
        MULTICLASS_LABEL_NAMES,
    )


def hierarchical_multiclass_from_binary(binary_prob_dict, multiclass_prob_dict, threshold=0.5):
    if not binary_prob_dict or not multiclass_prob_dict:
        return None
    binary_avg = average_probabilities(binary_prob_dict)
    multiclass_avg = average_probabilities(multiclass_prob_dict)
    preds = []
    for fake_prob, class_probs in zip(binary_avg[:, 0], multiclass_avg):
        if fake_prob >= threshold:
            candidates = np.array([0, 1, 2])
        else:
            candidates = np.array([3, 4, 5])
        preds.append(candidates[np.argmax(class_probs[candidates])])
    return np.asarray(preds)


def tune_hierarchical_threshold_binary_plus_multiclass(binary_valid_prob_dict, multiclass_valid_prob_dict, y_valid):
    rows = []
    for threshold in np.linspace(0.20, 0.80, 121):
        preds = hierarchical_multiclass_from_binary(binary_valid_prob_dict, multiclass_valid_prob_dict, threshold)
        rows.append({
            "threshold": float(threshold),
            "accuracy": accuracy_score(y_valid, preds),
            "macro_recall": recall_score(y_valid, preds, average="macro", zero_division=0),
            "macro_f1": f1_score(y_valid, preds, average="macro", zero_division=0),
        })
    table = pd.DataFrame(rows)
    best = table.sort_values(["macro_f1", "accuracy", "macro_recall"], ascending=False).iloc[0]
    return best, table


if "binary_valid_probs" in globals() and binary_valid_probs and multiclass_valid_probs:
    hierarchical_best_threshold, hierarchical_threshold_table = tune_hierarchical_threshold_binary_plus_multiclass(
        binary_valid_probs,
        multiclass_valid_probs,
        y_valid_multi,
    )
    print("\nBest hierarchical binary + six-class validation threshold")
    print(hierarchical_best_threshold.round(4).to_string())

    hierarchical_multiclass_test_preds = hierarchical_multiclass_from_binary(
        binary_test_probs,
        multiclass_test_probs,
        threshold=hierarchical_best_threshold["threshold"],
    )
    hierarchical_multiclass_summary = print_report(
        "multiclass test - Hierarchical binary + six-class ensemble",
        y_test_multi,
        hierarchical_multiclass_test_preds,
        MULTICLASS_LABEL_NAMES,
        "multiclass",
    )


# Specialized hierarchy: binary gate + separate fake-subtype and real-subtype transformer ensembles.
fake_subtype_ready_artifacts = get_ready_artifacts("fake_subtype", HIERARCHICAL_SUBTYPE_MODELS)
real_subtype_ready_artifacts = get_ready_artifacts("real_subtype", HIERARCHICAL_SUBTYPE_MODELS)

if fake_subtype_ready_artifacts and real_subtype_ready_artifacts and binary_valid_probs:
    fake_subtype_valid_all_probs = collect_probabilities_for_texts(
        fake_subtype_ready_artifacts,
        multiclass_splits["valid"]["texts"],
        num_labels=len(FAKE_SUBTYPE_LABEL_NAMES),
        split_name="multiclass-valid fake-subtype",
        max_length=160,
    )
    fake_subtype_test_all_probs = collect_probabilities_for_texts(
        fake_subtype_ready_artifacts,
        multiclass_splits["test"]["texts"],
        num_labels=len(FAKE_SUBTYPE_LABEL_NAMES),
        split_name="multiclass-test fake-subtype",
        max_length=160,
    )
    real_subtype_valid_all_probs = collect_probabilities_for_texts(
        real_subtype_ready_artifacts,
        multiclass_splits["valid"]["texts"],
        num_labels=len(REAL_SUBTYPE_LABEL_NAMES),
        split_name="multiclass-valid real-subtype",
        max_length=160,
    )
    real_subtype_test_all_probs = collect_probabilities_for_texts(
        real_subtype_ready_artifacts,
        multiclass_splits["test"]["texts"],
        num_labels=len(REAL_SUBTYPE_LABEL_NAMES),
        split_name="multiclass-test real-subtype",
        max_length=160,
    )

    def specialized_hierarchical_predictions(binary_prob_dict, fake_prob_dict, real_prob_dict, threshold=0.5):
        binary_avg = average_probabilities(binary_prob_dict)
        fake_avg = average_probabilities(fake_prob_dict)
        real_avg = average_probabilities(real_prob_dict)
        preds = []
        for fake_gate_prob, fake_probs, real_probs in zip(binary_avg[:, 0], fake_avg, real_avg):
            if fake_gate_prob >= threshold:
                preds.append(int(np.argmax(fake_probs)))
            else:
                preds.append(int(np.argmax(real_probs)) + 3)
        return np.asarray(preds)

    def tune_specialized_hierarchical_threshold(binary_prob_dict, fake_prob_dict, real_prob_dict, y_valid):
        rows = []
        for threshold in np.linspace(0.20, 0.80, 121):
            preds = specialized_hierarchical_predictions(binary_prob_dict, fake_prob_dict, real_prob_dict, threshold)
            rows.append({
                "threshold": float(threshold),
                "accuracy": accuracy_score(y_valid, preds),
                "macro_recall": recall_score(y_valid, preds, average="macro", zero_division=0),
                "macro_f1": f1_score(y_valid, preds, average="macro", zero_division=0),
            })
        table = pd.DataFrame(rows)
        best = table.sort_values(["macro_f1", "accuracy", "macro_recall"], ascending=False).iloc[0]
        return best, table

    specialized_hierarchical_best_threshold, specialized_hierarchical_threshold_table = tune_specialized_hierarchical_threshold(
        binary_valid_probs,
        fake_subtype_valid_all_probs,
        real_subtype_valid_all_probs,
        y_valid_multi,
    )
    print("\nBest specialized hierarchical validation threshold")
    print(specialized_hierarchical_best_threshold.round(4).to_string())

    specialized_hierarchical_test_preds = specialized_hierarchical_predictions(
        binary_test_probs,
        fake_subtype_test_all_probs,
        real_subtype_test_all_probs,
        threshold=specialized_hierarchical_best_threshold["threshold"],
    )
    specialized_hierarchical_summary = print_report(
        "multiclass test - Specialized hierarchical binary + subtype ensembles",
        y_test_multi,
        specialized_hierarchical_test_preds,
        MULTICLASS_LABEL_NAMES,
        "multiclass",
    )


multiclass_predictions_for_report = {}
for model_name, probs in sorted(multiclass_test_probs.items()):
    multiclass_predictions_for_report[f"Individual: {model_name}"] = probs.argmax(axis=1)
for key, label in [
    ("majority_vote", "Ensemble: majority vote"),
    ("highest_sum", "Ensemble: highest-sum / avg prob"),
    ("validation_weighted", "Ensemble: validation-weighted avg prob"),
    ("validation_selected_avg", "Ensemble: validation-selected avg prob"),
]:
    if key in multiclass_test_ensemble:
        multiclass_predictions_for_report[label] = multiclass_test_ensemble[key]["preds"]
if isinstance(multiclass_stacked_results, dict) and "tfidf_test_preds" in multiclass_stacked_results:
    multiclass_predictions_for_report["Baseline: TF-IDF + metadata"] = multiclass_stacked_results["tfidf_test_preds"]
if isinstance(multiclass_stacked_results, dict) and "credibility_test_preds" in multiclass_stacked_results:
    multiclass_predictions_for_report["Baseline: LIAR credibility"] = multiclass_stacked_results["credibility_test_preds"]
if isinstance(multiclass_stacked_results, dict) and "meta_test_preds" in multiclass_stacked_results:
    multiclass_predictions_for_report["Ensemble: stacked transformer + credibility meta"] = multiclass_stacked_results["meta_test_preds"]
if "multiclass_gnn_results" in globals():
    multiclass_predictions_for_report["GNN: LIAR metadata graph"] = multiclass_gnn_results["test_preds"]
if "multiclass_gnn_blend_results" in globals():
    multiclass_predictions_for_report["Ensemble: transformer + LIAR metadata GNN"] = multiclass_gnn_blend_results["test_preds"]
if "hierarchical_multiclass_test_preds" in globals():
    multiclass_predictions_for_report["Ensemble: hierarchical binary + six-class"] = hierarchical_multiclass_test_preds
if "specialized_hierarchical_test_preds" in globals():
    multiclass_predictions_for_report["Ensemble: specialized hierarchical subtype"] = specialized_hierarchical_test_preds

Predicting probabilities: distilbert-base-uncased [multiclass] (max_length=128, batch_size=32)

Loading weights: 100%|█████████████████████████████████████████████████████████████| 104/104 [00:00<00:00, 5200.13it/s]
Loading weights: 100%|█████████████████████████████████████████████████████████████| 104/104 [00:00<00:00, 5778.43it/s]

Predicting probabilities: bert-base-uncased [multiclass] (max_length=128, batch_size=32)

Loading weights: 100%|█████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 4902.77it/s]
Loading weights: 100%|█████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 4674.26it/s]

Predicting probabilities: roberta-base [multiclass] (max_length=128, batch_size=32)

Loading weights: 100%|█████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 4902.77it/s]
Loading weights: 100%|█████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 4784.38it/s]

multiclass test - Majority vote
accuracy           0.4412
macro_recall       0.4689
weighted_recall    0.4412
macro_f1           0.4465
weighted_f1        0.4364
              precision    recall  f1-score   support

  pants-fire       0.43      0.72      0.54        92
       false       0.61      0.30      0.41       250
 barely-true       0.42      0.45      0.43       214
   half-true       0.41      0.44      0.42       267
 mostly-true       0.42      0.52      0.46       249
        true       0.47      0.37      0.42       211

    accuracy                           0.44      1283
   macro avg       0.46      0.47      0.45      1283
weighted avg       0.46      0.44      0.44      1283


multiclass test - Highest-sum / averaged probabilities
accuracy           0.4419
macro_recall       0.4719
weighted_recall    0.4419
macro_f1           0.4461
weighted_f1        0.4358
              precision    recall  f1-score   support

  pants-fire       0.43      0.73      0.54        92
       false       0.60      0.32      0.41       250
 barely-true       0.40      0.46      0.43       214
   half-true       0.45      0.37      0.41       267
 mostly-true       0.41      0.58      0.48       249
        true       0.45      0.38      0.41       211

    accuracy                           0.44      1283
   macro avg       0.46      0.47      0.45      1283
weighted avg       0.46      0.44      0.44      1283


multiclass test - Validation-weighted probability ensemble
accuracy           0.4396
macro_recall       0.4699
weighted_recall    0.4396
macro_f1           0.4438
weighted_f1        0.4336
              precision    recall  f1-score   support

  pants-fire       0.42      0.73      0.54        92
       false       0.60      0.31      0.41       250
 barely-true       0.39      0.46      0.42       214
   half-true       0.46      0.37      0.41       267
 mostly-true       0.41      0.57      0.47       249
        true       0.44      0.38      0.41       211

    accuracy                           0.44      1283
   macro avg       0.45      0.47      0.44      1283
weighted avg       0.46      0.44      0.43      1283


multiclass test - Validation-selected averaged probabilities ('distilbert-base-uncased [multiclass]', 'roberta-base [multiclass]')
accuracy           0.4162
macro_recall       0.4424
weighted_recall    0.4162
macro_f1           0.4196
weighted_f1        0.4114
              precision    recall  f1-score   support

  pants-fire       0.39      0.66      0.49        92
       false       0.53      0.30      0.38       250
 barely-true       0.36      0.46      0.41       214
   half-true       0.43      0.36      0.39       267
 mostly-true       0.39      0.52      0.45       249
        true       0.47      0.35      0.40       211

    accuracy                           0.42      1283
   macro avg       0.43      0.44      0.42      1283
weighted avg       0.43      0.42      0.41      1283


multiclass valid - TF-IDF LogisticRegression baseline
accuracy           0.3076
macro_recall       0.3222
weighted_recall    0.3076
macro_f1           0.3147
weighted_f1        0.3061
              precision    recall  f1-score   support

  pants-fire       0.39      0.48      0.43       116
       false       0.38      0.37      0.38       263
 barely-true       0.27      0.24      0.26       237
   half-true       0.29      0.28      0.29       248
 mostly-true       0.28      0.25      0.26       251
        true       0.24      0.31      0.27       169

    accuracy                           0.31      1284
   macro avg       0.31      0.32      0.31      1284
weighted avg       0.31      0.31      0.31      1284


multiclass test - TF-IDF LogisticRegression baseline
accuracy           0.3001
macro_recall       0.3173
weighted_recall    0.3001
macro_f1           0.3068
weighted_f1        0.2973
              precision    recall  f1-score   support

  pants-fire       0.34      0.46      0.39        92
       false       0.39      0.37      0.38       250
 barely-true       0.25      0.22      0.23       214
   half-true       0.26      0.22      0.24       267
 mostly-true       0.27      0.27      0.27       249
        true       0.30      0.37      0.33       211

    accuracy                           0.30      1283
   macro avg       0.30      0.32      0.31      1283
weighted avg       0.30      0.30      0.30      1283


multiclass valid - LIAR credibility baseline
accuracy           0.4104
macro_recall       0.4185
weighted_recall    0.4104
macro_f1           0.4120
weighted_f1        0.4110
              precision    recall  f1-score   support

  pants-fire       0.42      0.53      0.47       116
       false       0.46      0.40      0.43       263
 barely-true       0.43      0.42      0.43       237
   half-true       0.38      0.37      0.37       248
 mostly-true       0.45      0.43      0.44       251
        true       0.31      0.37      0.34       169

    accuracy                           0.41      1284
   macro avg       0.41      0.42      0.41      1284
weighted avg       0.41      0.41      0.41      1284


multiclass test - LIAR credibility baseline
accuracy           0.4123
macro_recall       0.4352
weighted_recall    0.4123
macro_f1           0.4206
weighted_f1        0.4111
              precision    recall  f1-score   support

  pants-fire       0.43      0.63      0.51        92
       false       0.48      0.42      0.45       250
 barely-true       0.38      0.38      0.38       214
   half-true       0.42      0.34      0.38       267
 mostly-true       0.44      0.43      0.43       249
        true       0.34      0.41      0.37       211

    accuracy                           0.41      1283
   macro avg       0.41      0.44      0.42      1283
weighted avg       0.42      0.41      0.41      1283


multiclass test - Stacked meta ensemble
accuracy           0.4482
macro_recall       0.4724
weighted_recall    0.4482
macro_f1           0.4546
weighted_f1        0.4474
              precision    recall  f1-score   support

  pants-fire       0.44      0.70      0.54        92
       false       0.54      0.44      0.49       250
 barely-true       0.41      0.44      0.43       214
   half-true       0.46      0.43      0.45       267
 mostly-true       0.47      0.45      0.46       249
        true       0.36      0.37      0.37       211

    accuracy                           0.45      1283
   macro avg       0.45      0.47      0.45      1283
weighted avg       0.45      0.45      0.45      1283


multiclass valid - LIAR metadata GNN
accuracy           0.4626
macro_recall       0.4637
weighted_recall    0.4626
macro_f1           0.4564
weighted_f1        0.4604
              precision    recall  f1-score   support

  pants-fire       0.47      0.59      0.52       116
       false       0.53      0.49      0.51       263
 barely-true       0.46      0.49      0.48       237
   half-true       0.44      0.45      0.44       248
 mostly-true       0.51      0.49      0.50       251
        true       0.32      0.27      0.29       169

    accuracy                           0.46      1284
   macro avg       0.45      0.46      0.46      1284
weighted avg       0.46      0.46      0.46      1284


multiclass test - LIAR metadata GNN
accuracy           0.4380
macro_recall       0.4636
weighted_recall    0.4380
macro_f1           0.4427
weighted_f1        0.4319
              precision    recall  f1-score   support

  pants-fire       0.47      0.73      0.57        92
       false       0.47      0.48      0.48       250
 barely-true       0.40      0.43      0.42       214
   half-true       0.46      0.44      0.45       267
 mostly-true       0.44      0.45      0.44       249
        true       0.37      0.25      0.30       211

    accuracy                           0.44      1283
   macro avg       0.43      0.46      0.44      1283
weighted avg       0.43      0.44      0.43      1283


multiclass test - Transformer + LIAR metadata GNN blend
accuracy           0.4482
macro_recall       0.4753
weighted_recall    0.4482
macro_f1           0.4530
weighted_f1        0.4446
              precision    recall  f1-score   support

  pants-fire       0.43      0.73      0.54        92
       false       0.55      0.42      0.48       250
 barely-true       0.43      0.45      0.44       214
   half-true       0.46      0.40      0.43       267
 mostly-true       0.40      0.53      0.46       249
        true       0.43      0.33      0.37       211

    accuracy                           0.45      1283
   macro avg       0.45      0.48      0.45      1283
weighted avg       0.46      0.45      0.44      1283

Best GNN blend alpha on validation: 0.64

Best hierarchical binary + six-class validation threshold
threshold       0.3650
accuracy        0.4844
macro_recall    0.4911
macro_f1        0.4781

multiclass test - Hierarchical binary + six-class ensemble
accuracy           0.4419
macro_recall       0.4724
weighted_recall    0.4419
macro_f1           0.4447
weighted_f1        0.4350
              precision    recall  f1-score   support

  pants-fire       0.42      0.72      0.53        92
       false       0.48      0.42      0.45       250
 barely-true       0.36      0.57      0.44       214
   half-true       0.58      0.30      0.39       267
 mostly-true       0.43      0.52      0.47       249
        true       0.50      0.32      0.39       211

    accuracy                           0.44      1283
   macro avg       0.46      0.47      0.44      1283
weighted avg       0.47      0.44      0.44      1283

Predicting multiclass-valid fake-subtype probabilities: distilbert-base-uncased [fake_subtype] (max_length=128, batch_size=32)

Loading weights: 100%|█████████████████████████████████████████████████████████████| 104/104 [00:00<00:00, 6501.05it/s]

Predicting multiclass-test fake-subtype probabilities: distilbert-base-uncased [fake_subtype] (max_length=128, batch_size=32)

Loading weights: 100%|█████████████████████████████████████████████████████████████| 104/104 [00:00<00:00, 5200.07it/s]

Predicting multiclass-valid real-subtype probabilities: distilbert-base-uncased [real_subtype] (max_length=128, batch_size=32)

Loading weights: 100%|█████████████████████████████████████████████████████████████| 104/104 [00:00<00:00, 4163.24it/s]

Predicting multiclass-test real-subtype probabilities: distilbert-base-uncased [real_subtype] (max_length=128, batch_size=32)

Loading weights: 100%|█████████████████████████████████████████████████████████████| 104/104 [00:00<00:00, 4727.10it/s]

Best specialized hierarchical validation threshold
threshold       0.4450
accuracy        0.4836
macro_recall    0.4929
macro_f1        0.4776

multiclass test - Specialized hierarchical binary + subtype ensembles
accuracy           0.4451
macro_recall       0.4683
weighted_recall    0.4451
macro_f1           0.4440
weighted_f1        0.4416
              precision    recall  f1-score   support

  pants-fire       0.38      0.71      0.49        92
       false       0.47      0.43      0.45       250
 barely-true       0.40      0.38      0.39       214
   half-true       0.51      0.43      0.46       267
 mostly-true       0.43      0.53      0.48       249
        true       0.49      0.33      0.39       211

    accuracy                           0.45      1283
   macro avg       0.45      0.47      0.44      1283
weighted avg       0.45      0.45      0.44      1283

In [14]:
# Save a compact experiment summary for comparison across runs.
summary = {
    "binary_models": [
        {
            "model_name": a.get("model_name"),
            "run_dir": str(a.get("run_dir")),
            "valid_metrics": a.get("valid_metrics", {}),
            "test_metrics": a.get("test_metrics", {}),
        }
        for a in binary_artifacts
    ],
    "binary_threshold": best_accuracy_threshold.to_dict() if "best_accuracy_threshold" in globals() else None,
    "binary_threshold_test_summary": threshold_test_summary if "threshold_test_summary" in globals() else None,
    "binary_stacked": binary_stacked_results if "binary_stacked_results" in globals() else None,
    "multiclass_stacked": multiclass_stacked_results if "multiclass_stacked_results" in globals() else None,
    "multiclass_models": [
        {
            "model_name": a.get("model_name"),
            "run_dir": str(a.get("run_dir")),
            "valid_metrics": a.get("valid_metrics", {}),
            "test_metrics": a.get("test_metrics", {}),
        }
        for a in multiclass_artifacts
    ],
}

summary_path = SUMMARY_DIR / "optimized_liar_summary.json"
with open(summary_path, "w", encoding="utf-8") as f:
    json.dump(summary, f, indent=2, default=str)

print(f"Saved summary to {summary_path}")

Saved summary to C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\optimized_liar_summary.json

In [15]:
# ===== Final structured tables for report =====
# Run this after the binary and multiclass ensemble evaluation cells.

def row_from_predictions(task_name, split_name, method, y_true, y_pred):
    row = {
        "task": task_name,
        "split": split_name,
        "method": method,
        "accuracy": accuracy_score(y_true, y_pred),
        "macro_recall": recall_score(y_true, y_pred, average="macro", zero_division=0),
        "weighted_recall": recall_score(y_true, y_pred, average="weighted", zero_division=0),
        "macro_f1": f1_score(y_true, y_pred, average="macro", zero_division=0),
        "weighted_f1": f1_score(y_true, y_pred, average="weighted", zero_division=0),
    }
    if task_name == "binary":
        row["fake_recall"] = recall_score(y_true, y_pred, pos_label=0, zero_division=0)
        row["real_recall"] = recall_score(y_true, y_pred, pos_label=1, zero_division=0)
    return row


def make_results_table(task_name, y_true, prediction_dict):
    rows = [
        row_from_predictions(task_name, "test", method, y_true, y_pred)
        for method, y_pred in prediction_dict.items()
    ]
    table = pd.DataFrame(rows)
    metric_cols = [c for c in ["accuracy", "macro_recall", "weighted_recall", "macro_f1", "weighted_f1", "fake_recall", "real_recall"] if c in table.columns]
    table[metric_cols] = table[metric_cols].astype(float).round(4)
    return table.sort_values(["accuracy", "macro_f1"], ascending=False).reset_index(drop=True)


binary_results_table = make_results_table(
    "binary",
    y_test_binary,
    binary_predictions_for_report if "binary_predictions_for_report" in globals() else {},
)

multiclass_results_table = make_results_table(
    "multiclass",
    y_test_multi,
    multiclass_predictions_for_report if "multiclass_predictions_for_report" in globals() else {},
)

SUMMARY_DIR.mkdir(parents=True, exist_ok=True)
binary_table_path = SUMMARY_DIR / "binary_results_table.csv"
multiclass_table_path = SUMMARY_DIR / "multiclass_results_table.csv"
binary_results_table.to_csv(binary_table_path, index=False)
multiclass_results_table.to_csv(multiclass_table_path, index=False)

if "threshold_table" in globals():
    threshold_table.round(4).to_csv(SUMMARY_DIR / "binary_threshold_tuning_table.csv", index=False)
if "hierarchical_threshold_table" in globals():
    hierarchical_threshold_table.round(4).to_csv(SUMMARY_DIR / "hierarchical_threshold_tuning_table.csv", index=False)
if "specialized_hierarchical_threshold_table" in globals():
    specialized_hierarchical_threshold_table.round(4).to_csv(SUMMARY_DIR / "specialized_hierarchical_threshold_tuning_table.csv", index=False)

print("Binary report table")
display(binary_results_table)
if len(binary_results_table):
    best_binary_row = binary_results_table.iloc[0]
    best_binary_accuracy = float(best_binary_row["accuracy"])
    if best_binary_accuracy >= 0.80:
        print(f"\nBINARY TARGET REACHED: {best_binary_accuracy:.4f} accuracy using {best_binary_row['method']}")
    else:
        print(f"\nBinary best is {best_binary_accuracy:.4f}; gap to 0.8000 is {0.80 - best_binary_accuracy:.4f}.")
print(f"Saved: {binary_table_path}")

print("\nMulticlass report table")
display(multiclass_results_table)
print(f"Saved: {multiclass_table_path}")

Binary report table

,task,split,method,accuracy,macro_recall,weighted_recall,macro_f1,weighted_f1,fake_recall,real_recall
0,binary,test,Ensemble: validation-selected avg prob,0.7646,0.7568,0.7646,0.7584,0.7636,0.6978,0.8157
1,binary,test,Ensemble: validation-selected + tuned threshold,0.7646,0.7568,0.7646,0.7584,0.7636,0.6978,0.8157
2,binary,test,Ensemble: majority vote,0.7607,0.7542,0.7607,0.7552,0.7601,0.7050,0.8033
3,binary,test,Ensemble: highest-sum / avg prob,0.7607,0.7542,0.7607,0.7552,0.7601,0.7050,0.8033
4,binary,test,Ensemble: validation-weighted avg prob,0.7599,0.7535,0.7599,0.7545,0.7594,0.7050,0.8019
5,binary,test,Ensemble: transformer + LIAR metadata GNN,0.7576,0.7516,0.7576,0.7524,0.7572,0.7068,0.7964
6,binary,test,Individual: roberta-base [binary_refit],0.7537,0.7469,0.7537,0.7480,0.7531,0.6960,0.7978
7,binary,test,Individual: roberta-base [binary],0.7529,0.7488,0.7529,0.7486,0.7530,0.7176,0.7799
8,binary,test,Individual: distilbert-base-uncased [binary_re...,0.7521,0.7477,0.7521,0.7477,0.7521,0.7140,0.7813
9,binary,test,Individual: distilbert-base-uncased [binary],0.7514,0.7463,0.7514,0.7466,0.7512,0.7086,0.7840
10,binary,test,Individual: bert-base-uncased [binary_refit],0.7490,0.7379,0.7490,0.7405,0.7467,0.6547,0.8212
11,binary,test,Individual: bert-base-uncased [binary],0.7443,0.7429,0.7443,0.7412,0.7450,0.7320,0.7538
12,binary,test,Ensemble: stacked transformer + credibility meta,0.7436,0.7392,0.7436,0.7391,0.7436,0.7068,0.7717
13,binary,test,Baseline: LIAR credibility,0.7295,0.7269,0.7295,0.7258,0.7301,0.7068,0.7469
14,binary,test,GNN: LIAR metadata graph,0.7288,0.7291,0.7288,0.7263,0.7298,0.7320,0.7263
15,binary,test,Baseline: TF-IDF + metadata,0.6617,0.6541,0.6617,0.6545,0.6612,0.5971,0.7111

Binary best is 0.7646; gap to 0.8000 is 0.0354.
Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\binary_results_table.csv

Multiclass report table

,task,split,method,accuracy,macro_recall,weighted_recall,macro_f1,weighted_f1
0,multiclass,test,Ensemble: stacked transformer + credibility meta,0.4482,0.4724,0.4482,0.4546,0.4474
1,multiclass,test,Ensemble: transformer + LIAR metadata GNN,0.4482,0.4753,0.4482,0.4530,0.4446
2,multiclass,test,Ensemble: specialized hierarchical subtype,0.4451,0.4683,0.4451,0.4440,0.4416
3,multiclass,test,Individual: bert-base-uncased [multiclass],0.4443,0.4743,0.4443,0.4499,0.4398
4,multiclass,test,Ensemble: highest-sum / avg prob,0.4419,0.4719,0.4419,0.4461,0.4358
5,multiclass,test,Ensemble: hierarchical binary + six-class,0.4419,0.4724,0.4419,0.4447,0.4350
6,multiclass,test,Ensemble: majority vote,0.4412,0.4689,0.4412,0.4465,0.4364
7,multiclass,test,Ensemble: validation-weighted avg prob,0.4396,0.4699,0.4396,0.4438,0.4336
8,multiclass,test,GNN: LIAR metadata graph,0.4380,0.4636,0.4380,0.4427,0.4319
9,multiclass,test,Individual: distilbert-base-uncased [multiclass],0.4170,0.4444,0.4170,0.4194,0.4116
10,multiclass,test,Ensemble: validation-selected avg prob,0.4162,0.4424,0.4162,0.4196,0.4114
11,multiclass,test,Baseline: LIAR credibility,0.4123,0.4352,0.4123,0.4206,0.4111
12,multiclass,test,Baseline: TF-IDF + metadata,0.3001,0.3173,0.3001,0.3068,0.2973
13,multiclass,test,Individual: roberta-base [multiclass],0.2081,0.1667,0.2081,0.0574,0.0717

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\multiclass_results_table.csv

In [16]:
from sklearn.metrics import classification_report
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 240)


def safe_filename(name):
    return (
        name.replace("/", "_")
            .replace(":", "")
            .replace(" ", "_")
            .replace("-", "_")
            .lower()
    )


def make_separate_per_class_tables(y_true, prediction_dict, label_names, task_name):
    all_tables = {}
    task_dir = SUMMARY_DIR / f"{task_name}_per_class_tables"
    task_dir.mkdir(parents=True, exist_ok=True)

    for method, y_pred in prediction_dict.items():
        report = classification_report(
            y_true,
            y_pred,
            target_names=label_names,
            output_dict=True,
            zero_division=0,
        )
        table = pd.DataFrame(report).T.round(4)
        table = table.loc[label_names + ["accuracy", "macro avg", "weighted avg"]]

        path = task_dir / f"{safe_filename(method)}.csv"
        table.to_csv(path)

        print("\n" + "=" * 80)
        print(f"{task_name.upper()} - {method}")
        print("=" * 80)
        display(table)
        print("Saved:", path)
        all_tables[method] = table

    long_rows = []
    for method, table in all_tables.items():
        for label in label_names:
            long_rows.append({
                "task": task_name,
                "method": method,
                "class": label,
                "precision": table.loc[label, "precision"],
                "recall": table.loc[label, "recall"],
                "f1_score": table.loc[label, "f1-score"],
                "support": table.loc[label, "support"],
            })
    long_table = pd.DataFrame(long_rows)
    long_path = SUMMARY_DIR / f"{task_name}_per_class_report_long.csv"
    long_table.to_csv(long_path, index=False)
    print("\nSaved long per-class table:", long_path)
    display(long_table)
    return all_tables, long_table


binary_separate_tables, binary_per_class_long = make_separate_per_class_tables(
    y_true=y_test_binary,
    prediction_dict=binary_predictions_for_report,
    label_names=BINARY_LABEL_NAMES,
    task_name="binary",
)

multiclass_separate_tables, multiclass_per_class_long = make_separate_per_class_tables(
    y_true=y_test_multi,
    prediction_dict=multiclass_predictions_for_report,
    label_names=MULTICLASS_LABEL_NAMES,
    task_name="multiclass",
)

================================================================================
BINARY - Individual: bert-base-uncased [binary]
================================================================================

              precision  recall  f1-score    support
fake             0.6945  0.7320    0.7128   556.0000
real             0.7862  0.7538    0.7697   727.0000
accuracy         0.7443  0.7443    0.7443     0.7443
macro avg        0.7404  0.7429    0.7412  1283.0000
weighted avg     0.7465  0.7443    0.7450  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\binary_per_class_tables\individual_bert_base_uncased_[binary].csv

================================================================================
BINARY - Individual: bert-base-uncased [binary_refit]
================================================================================

              precision  recall  f1-score   support
fake             0.7368  0.6547    0.6933   556.000
real             0.7567  0.8212    0.7876   727.000
accuracy         0.7490  0.7490    0.7490     0.749
macro avg        0.7467  0.7379    0.7405  1283.000
weighted avg     0.7481  0.7490    0.7467  1283.000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\binary_per_class_tables\individual_bert_base_uncased_[binary_refit].csv

================================================================================
BINARY - Individual: distilbert-base-uncased [binary]
================================================================================

              precision  recall  f1-score    support
fake             0.7151  0.7086    0.7118   556.0000
real             0.7787  0.7840    0.7814   727.0000
accuracy         0.7514  0.7514    0.7514     0.7514
macro avg        0.7469  0.7463    0.7466  1283.0000
weighted avg     0.7511  0.7514    0.7512  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\binary_per_class_tables\individual_distilbert_base_uncased_[binary].csv

================================================================================
BINARY - Individual: distilbert-base-uncased [binary_refit]
================================================================================

              precision  recall  f1-score    support
fake             0.7140  0.7140    0.7140   556.0000
real             0.7813  0.7813    0.7813   727.0000
accuracy         0.7521  0.7521    0.7521     0.7521
macro avg        0.7477  0.7477    0.7477  1283.0000
weighted avg     0.7521  0.7521    0.7521  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\binary_per_class_tables\individual_distilbert_base_uncased_[binary_refit].csv

================================================================================
BINARY - Individual: roberta-base [binary]
================================================================================

              precision  recall  f1-score    support
fake             0.7138  0.7176    0.7157   556.0000
real             0.7831  0.7799    0.7815   727.0000
accuracy         0.7529  0.7529    0.7529     0.7529
macro avg        0.7485  0.7488    0.7486  1283.0000
weighted avg     0.7531  0.7529    0.7530  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\binary_per_class_tables\individual_roberta_base_[binary].csv

================================================================================
BINARY - Individual: roberta-base [binary_refit]
================================================================================

              precision  recall  f1-score    support
fake             0.7247  0.6960    0.7101   556.0000
real             0.7744  0.7978    0.7859   727.0000
accuracy         0.7537  0.7537    0.7537     0.7537
macro avg        0.7495  0.7469    0.7480  1283.0000
weighted avg     0.7529  0.7537    0.7531  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\binary_per_class_tables\individual_roberta_base_[binary_refit].csv

================================================================================
BINARY - Ensemble: majority vote
================================================================================

              precision  recall  f1-score    support
fake             0.7327  0.7050    0.7186   556.0000
real             0.7807  0.8033    0.7919   727.0000
accuracy         0.7607  0.7607    0.7607     0.7607
macro avg        0.7567  0.7542    0.7552  1283.0000
weighted avg     0.7599  0.7607    0.7601  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\binary_per_class_tables\ensemble_majority_vote.csv

================================================================================
BINARY - Ensemble: highest-sum / avg prob
================================================================================

              precision  recall  f1-score    support
fake             0.7327  0.7050    0.7186   556.0000
real             0.7807  0.8033    0.7919   727.0000
accuracy         0.7607  0.7607    0.7607     0.7607
macro avg        0.7567  0.7542    0.7552  1283.0000
weighted avg     0.7599  0.7607    0.7601  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\binary_per_class_tables\ensemble_highest_sum___avg_prob.csv

================================================================================
BINARY - Ensemble: validation-weighted avg prob
================================================================================

              precision  recall  f1-score    support
fake             0.7313  0.7050    0.7179   556.0000
real             0.7805  0.8019    0.7910   727.0000
accuracy         0.7599  0.7599    0.7599     0.7599
macro avg        0.7559  0.7535    0.7545  1283.0000
weighted avg     0.7592  0.7599    0.7594  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\binary_per_class_tables\ensemble_validation_weighted_avg_prob.csv

================================================================================
BINARY - Ensemble: validation-selected avg prob
================================================================================

              precision  recall  f1-score    support
fake             0.7433  0.6978    0.7199   556.0000
real             0.7792  0.8157    0.7970   727.0000
accuracy         0.7646  0.7646    0.7646     0.7646
macro avg        0.7613  0.7568    0.7584  1283.0000
weighted avg     0.7637  0.7646    0.7636  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\binary_per_class_tables\ensemble_validation_selected_avg_prob.csv

================================================================================
BINARY - Ensemble: validation-selected + tuned threshold
================================================================================

              precision  recall  f1-score    support
fake             0.7433  0.6978    0.7199   556.0000
real             0.7792  0.8157    0.7970   727.0000
accuracy         0.7646  0.7646    0.7646     0.7646
macro avg        0.7613  0.7568    0.7584  1283.0000
weighted avg     0.7637  0.7646    0.7636  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\binary_per_class_tables\ensemble_validation_selected_+_tuned_threshold.csv

================================================================================
BINARY - GNN: LIAR metadata graph
================================================================================

              precision  recall  f1-score    support
fake             0.6716  0.7320    0.7005   556.0000
real             0.7799  0.7263    0.7521   727.0000
accuracy         0.7288  0.7288    0.7288     0.7288
macro avg        0.7258  0.7291    0.7263  1283.0000
weighted avg     0.7330  0.7288    0.7298  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\binary_per_class_tables\gnn_liar_metadata_graph.csv

================================================================================
BINARY - Ensemble: transformer + LIAR metadata GNN
================================================================================

              precision  recall  f1-score    support
fake             0.7264  0.7068    0.7165   556.0000
real             0.7803  0.7964    0.7883   727.0000
accuracy         0.7576  0.7576    0.7576     0.7576
macro avg        0.7534  0.7516    0.7524  1283.0000
weighted avg     0.7570  0.7576    0.7572  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\binary_per_class_tables\ensemble_transformer_+_liar_metadata_gnn.csv

================================================================================
BINARY - Baseline: TF-IDF + metadata
================================================================================

              precision  recall  f1-score    support
fake             0.6125  0.5971    0.6047   556.0000
real             0.6977  0.7111    0.7044   727.0000
accuracy         0.6617  0.6617    0.6617     0.6617
macro avg        0.6551  0.6541    0.6545  1283.0000
weighted avg     0.6608  0.6617    0.6612  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\binary_per_class_tables\baseline_tf_idf_+_metadata.csv

================================================================================
BINARY - Baseline: LIAR credibility
================================================================================

              precision  recall  f1-score    support
fake             0.6811  0.7068    0.6937   556.0000
real             0.7691  0.7469    0.7579   727.0000
accuracy         0.7295  0.7295    0.7295     0.7295
macro avg        0.7251  0.7269    0.7258  1283.0000
weighted avg     0.7310  0.7295    0.7301  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\binary_per_class_tables\baseline_liar_credibility.csv

================================================================================
BINARY - Ensemble: stacked transformer + credibility meta
================================================================================

              precision  recall  f1-score    support
fake             0.7030  0.7068    0.7049   556.0000
real             0.7749  0.7717    0.7733   727.0000
accuracy         0.7436  0.7436    0.7436     0.7436
macro avg        0.7390  0.7392    0.7391  1283.0000
weighted avg     0.7437  0.7436    0.7436  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\binary_per_class_tables\ensemble_stacked_transformer_+_credibility_meta.csv

Saved long per-class table: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\binary_per_class_report_long.csv

      task                                             method class  precision  recall  f1_score  support
0   binary             Individual: bert-base-uncased [binary]  fake     0.6945  0.7320    0.7128    556.0
1   binary             Individual: bert-base-uncased [binary]  real     0.7862  0.7538    0.7697    727.0
2   binary       Individual: bert-base-uncased [binary_refit]  fake     0.7368  0.6547    0.6933    556.0
3   binary       Individual: bert-base-uncased [binary_refit]  real     0.7567  0.8212    0.7876    727.0
4   binary       Individual: distilbert-base-uncased [binary]  fake     0.7151  0.7086    0.7118    556.0
5   binary       Individual: distilbert-base-uncased [binary]  real     0.7787  0.7840    0.7814    727.0
6   binary  Individual: distilbert-base-uncased [binary_re...  fake     0.7140  0.7140    0.7140    556.0
7   binary  Individual: distilbert-base-uncased [binary_re...  real     0.7813  0.7813    0.7813    727.0
8   binary                  Individual: roberta-base [binary]  fake     0.7138  0.7176    0.7157    556.0
9   binary                  Individual: roberta-base [binary]  real     0.7831  0.7799    0.7815    727.0
10  binary            Individual: roberta-base [binary_refit]  fake     0.7247  0.6960    0.7101    556.0
11  binary            Individual: roberta-base [binary_refit]  real     0.7744  0.7978    0.7859    727.0
12  binary                            Ensemble: majority vote  fake     0.7327  0.7050    0.7186    556.0
13  binary                            Ensemble: majority vote  real     0.7807  0.8033    0.7919    727.0
14  binary                   Ensemble: highest-sum / avg prob  fake     0.7327  0.7050    0.7186    556.0
15  binary                   Ensemble: highest-sum / avg prob  real     0.7807  0.8033    0.7919    727.0
16  binary             Ensemble: validation-weighted avg prob  fake     0.7313  0.7050    0.7179    556.0
17  binary             Ensemble: validation-weighted avg prob  real     0.7805  0.8019    0.7910    727.0
18  binary             Ensemble: validation-selected avg prob  fake     0.7433  0.6978    0.7199    556.0
19  binary             Ensemble: validation-selected avg prob  real     0.7792  0.8157    0.7970    727.0
20  binary    Ensemble: validation-selected + tuned threshold  fake     0.7433  0.6978    0.7199    556.0
21  binary    Ensemble: validation-selected + tuned threshold  real     0.7792  0.8157    0.7970    727.0
22  binary                           GNN: LIAR metadata graph  fake     0.6716  0.7320    0.7005    556.0
23  binary                           GNN: LIAR metadata graph  real     0.7799  0.7263    0.7521    727.0
24  binary          Ensemble: transformer + LIAR metadata GNN  fake     0.7264  0.7068    0.7165    556.0
25  binary          Ensemble: transformer + LIAR metadata GNN  real     0.7803  0.7964    0.7883    727.0
26  binary                        Baseline: TF-IDF + metadata  fake     0.6125  0.5971    0.6047    556.0
27  binary                        Baseline: TF-IDF + metadata  real     0.6977  0.7111    0.7044    727.0
28  binary                         Baseline: LIAR credibility  fake     0.6811  0.7068    0.6937    556.0
29  binary                         Baseline: LIAR credibility  real     0.7691  0.7469    0.7579    727.0
30  binary   Ensemble: stacked transformer + credibility meta  fake     0.7030  0.7068    0.7049    556.0
31  binary   Ensemble: stacked transformer + credibility meta  real     0.7749  0.7717    0.7733    727.0

================================================================================
MULTICLASS - Individual: bert-base-uncased [multiclass]
================================================================================

              precision  recall  f1-score    support
pants-fire       0.4323  0.7283    0.5425    92.0000
false            0.5733  0.3440    0.4300   250.0000
barely-true      0.4409  0.4533    0.4470   214.0000
half-true        0.4802  0.3633    0.4136   267.0000
mostly-true      0.4119  0.5542    0.4726   249.0000
true             0.3846  0.4028    0.3935   211.0000
accuracy         0.4443  0.4443    0.4443     0.4443
macro avg        0.4539  0.4743    0.4499  1283.0000
weighted avg     0.4594  0.4443    0.4398  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\multiclass_per_class_tables\individual_bert_base_uncased_[multiclass].csv

================================================================================
MULTICLASS - Individual: distilbert-base-uncased [multiclass]
================================================================================

              precision  recall  f1-score   support
pants-fire       0.3804  0.6739    0.4863    92.000
false            0.5333  0.2880    0.3740   250.000
barely-true      0.3623  0.4673    0.4082   214.000
half-true        0.4419  0.3558    0.3942   267.000
mostly-true      0.3922  0.5261    0.4494   249.000
true             0.4688  0.3555    0.4043   211.000
accuracy         0.4170  0.4170    0.4170     0.417
macro avg        0.4298  0.4444    0.4194  1283.000
weighted avg     0.4368  0.4170    0.4116  1283.000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\multiclass_per_class_tables\individual_distilbert_base_uncased_[multiclass].csv

================================================================================
MULTICLASS - Individual: roberta-base [multiclass]
================================================================================

              precision  recall  f1-score    support
pants-fire       0.0000  0.0000    0.0000    92.0000
false            0.0000  0.0000    0.0000   250.0000
barely-true      0.0000  0.0000    0.0000   214.0000
half-true        0.2081  1.0000    0.3445   267.0000
mostly-true      0.0000  0.0000    0.0000   249.0000
true             0.0000  0.0000    0.0000   211.0000
accuracy         0.2081  0.2081    0.2081     0.2081
macro avg        0.0347  0.1667    0.0574  1283.0000
weighted avg     0.0433  0.2081    0.0717  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\multiclass_per_class_tables\individual_roberta_base_[multiclass].csv

================================================================================
MULTICLASS - Ensemble: majority vote
================================================================================

              precision  recall  f1-score    support
pants-fire       0.4286  0.7174    0.5366    92.0000
false            0.6080  0.3040    0.4053   250.0000
barely-true      0.4181  0.4533    0.4350   214.0000
half-true        0.4069  0.4419    0.4237   267.0000
mostly-true      0.4153  0.5221    0.4626   249.0000
true             0.4675  0.3744    0.4158   211.0000
accuracy         0.4412  0.4412    0.4412     0.4412
macro avg        0.4574  0.4689    0.4465  1283.0000
weighted avg     0.4611  0.4412    0.4364  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\multiclass_per_class_tables\ensemble_majority_vote.csv

================================================================================
MULTICLASS - Ensemble: highest-sum / avg prob
================================================================================

              precision  recall  f1-score    support
pants-fire       0.4268  0.7283    0.5382    92.0000
false            0.6031  0.3160    0.4147   250.0000
barely-true      0.3976  0.4626    0.4276   214.0000
half-true        0.4537  0.3670    0.4058   267.0000
mostly-true      0.4103  0.5783    0.4800   249.0000
true             0.4469  0.3791    0.4103   211.0000
accuracy         0.4419  0.4419    0.4419     0.4419
macro avg        0.4564  0.4719    0.4461  1283.0000
weighted avg     0.4620  0.4419    0.4358  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\multiclass_per_class_tables\ensemble_highest_sum___avg_prob.csv

================================================================================
MULTICLASS - Ensemble: validation-weighted avg prob
================================================================================

              precision  recall  f1-score    support
pants-fire       0.4241  0.7283    0.5360    92.0000
false            0.6047  0.3120    0.4116   250.0000
barely-true      0.3929  0.4626    0.4249   214.0000
half-true        0.4579  0.3670    0.4075   267.0000
mostly-true      0.4069  0.5703    0.4749   249.0000
true             0.4420  0.3791    0.4082   211.0000
accuracy         0.4396  0.4396    0.4396     0.4396
macro avg        0.4547  0.4699    0.4438  1283.0000
weighted avg     0.4607  0.4396    0.4336  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\multiclass_per_class_tables\ensemble_validation_weighted_avg_prob.csv

================================================================================
MULTICLASS - Ensemble: validation-selected avg prob
================================================================================

              precision  recall  f1-score    support
pants-fire       0.3885  0.6630    0.4900    92.0000
false            0.5319  0.3000    0.3836   250.0000
barely-true      0.3640  0.4626    0.4074   214.0000
half-true        0.4279  0.3558    0.3885   267.0000
mostly-true      0.3904  0.5221    0.4467   249.0000
true             0.4684  0.3507    0.4011   211.0000
accuracy         0.4162  0.4162    0.4162     0.4162
macro avg        0.4285  0.4424    0.4196  1283.0000
weighted avg     0.4341  0.4162    0.4114  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\multiclass_per_class_tables\ensemble_validation_selected_avg_prob.csv

================================================================================
MULTICLASS - Baseline: TF-IDF + metadata
================================================================================

              precision  recall  f1-score    support
pants-fire       0.3360  0.4565    0.3871    92.0000
false            0.3932  0.3680    0.3802   250.0000
barely-true      0.2500  0.2196    0.2338   214.0000
half-true        0.2564  0.2247    0.2395   267.0000
mostly-true      0.2739  0.2651    0.2694   249.0000
true             0.2989  0.3697    0.3305   211.0000
accuracy         0.3001  0.3001    0.3001     0.3001
macro avg        0.3014  0.3173    0.3068  1283.0000
weighted avg     0.2981  0.3001    0.2973  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\multiclass_per_class_tables\baseline_tf_idf_+_metadata.csv

================================================================================
MULTICLASS - Baseline: LIAR credibility
================================================================================

              precision  recall  f1-score    support
pants-fire       0.4328  0.6304    0.5133    92.0000
false            0.4751  0.4200    0.4459   250.0000
barely-true      0.3814  0.3832    0.3823   214.0000
half-true        0.4182  0.3446    0.3778   267.0000
mostly-true      0.4398  0.4257    0.4327   249.0000
true             0.3413  0.4076    0.3715   211.0000
accuracy         0.4123  0.4123    0.4123     0.4123
macro avg        0.4148  0.4352    0.4206  1283.0000
weighted avg     0.4157  0.4123    0.4111  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\multiclass_per_class_tables\baseline_liar_credibility.csv

================================================================================
MULTICLASS - Ensemble: stacked transformer + credibility meta
================================================================================

              precision  recall  f1-score    support
pants-fire       0.4414  0.6957    0.5401    92.0000
false            0.5441  0.4440    0.4890   250.0000
barely-true      0.4130  0.4439    0.4279   214.0000
half-true        0.4637  0.4307    0.4466   267.0000
mostly-true      0.4684  0.4458    0.4568   249.0000
true             0.3607  0.3744    0.3674   211.0000
accuracy         0.4482  0.4482    0.4482     0.4482
macro avg        0.4486  0.4724    0.4546  1283.0000
weighted avg     0.4533  0.4482    0.4474  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\multiclass_per_class_tables\ensemble_stacked_transformer_+_credibility_meta.csv

================================================================================
MULTICLASS - GNN: LIAR metadata graph
================================================================================

              precision  recall  f1-score   support
pants-fire       0.4718  0.7283    0.5726    92.000
false            0.4706  0.4800    0.4752   250.000
barely-true      0.4026  0.4346    0.4180   214.000
half-true        0.4627  0.4419    0.4521   267.000
mostly-true      0.4353  0.4458    0.4405   249.000
true             0.3655  0.2512    0.2978   211.000
accuracy         0.4380  0.4380    0.4380     0.438
macro avg        0.4348  0.4636    0.4427  1283.000
weighted avg     0.4336  0.4380    0.4319  1283.000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\multiclass_per_class_tables\gnn_liar_metadata_graph.csv

================================================================================
MULTICLASS - Ensemble: transformer + LIAR metadata GNN
================================================================================

              precision  recall  f1-score    support
pants-fire       0.4295  0.7283    0.5403    92.0000
false            0.5526  0.4200    0.4773   250.0000
barely-true      0.4344  0.4486    0.4414   214.0000
half-true        0.4629  0.3970    0.4274   267.0000
mostly-true      0.4043  0.5261    0.4572   249.0000
true             0.4294  0.3318    0.3743   211.0000
accuracy         0.4482  0.4482    0.4482     0.4482
macro avg        0.4522  0.4753    0.4530  1283.0000
weighted avg     0.4564  0.4482    0.4446  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\multiclass_per_class_tables\ensemble_transformer_+_liar_metadata_gnn.csv

================================================================================
MULTICLASS - Ensemble: hierarchical binary + six-class
================================================================================

              precision  recall  f1-score    support
pants-fire       0.4231  0.7174    0.5323    92.0000
false            0.4837  0.4160    0.4473   250.0000
barely-true      0.3612  0.5654    0.4408   214.0000
half-true        0.5766  0.2959    0.3911   267.0000
mostly-true      0.4262  0.5221    0.4693   249.0000
true             0.4963  0.3175    0.3873   211.0000
accuracy         0.4419  0.4419    0.4419     0.4419
macro avg        0.4612  0.4724    0.4447  1283.0000
weighted avg     0.4692  0.4419    0.4350  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\multiclass_per_class_tables\ensemble_hierarchical_binary_+_six_class.csv

================================================================================
MULTICLASS - Ensemble: specialized hierarchical subtype
================================================================================

              precision  recall  f1-score    support
pants-fire       0.3757  0.7065    0.4906    92.0000
false            0.4696  0.4320    0.4500   250.0000
barely-true      0.4020  0.3832    0.3923   214.0000
half-true        0.5067  0.4270    0.4634   267.0000
mostly-true      0.4290  0.5341    0.4758   249.0000
true             0.4894  0.3270    0.3920   211.0000
accuracy         0.4451  0.4451    0.4451     0.4451
macro avg        0.4454  0.4683    0.4440  1283.0000
weighted avg     0.4547  0.4451    0.4416  1283.0000

Saved: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\multiclass_per_class_tables\ensemble_specialized_hierarchical_subtype.csv

Saved long per-class table: C:\Users\Asus\Downloads\Fake news detection\code\optimized_summaries_simple_liar_novel_v7\multiclass_per_class_report_long.csv

          task                                      method        class  precision  recall  f1_score  support
0   multiclass  Individual: bert-base-uncased [multiclass]   pants-fire     0.4323  0.7283    0.5425     92.0
1   multiclass  Individual: bert-base-uncased [multiclass]        false     0.5733  0.3440    0.4300    250.0
2   multiclass  Individual: bert-base-uncased [multiclass]  barely-true     0.4409  0.4533    0.4470    214.0
3   multiclass  Individual: bert-base-uncased [multiclass]    half-true     0.4802  0.3633    0.4136    267.0
4   multiclass  Individual: bert-base-uncased [multiclass]  mostly-true     0.4119  0.5542    0.4726    249.0
..         ...                                         ...          ...        ...     ...       ...      ...
79  multiclass  Ensemble: specialized hierarchical subtype        false     0.4696  0.4320    0.4500    250.0
80  multiclass  Ensemble: specialized hierarchical subtype  barely-true     0.4020  0.3832    0.3923    214.0
81  multiclass  Ensemble: specialized hierarchical subtype    half-true     0.5067  0.4270    0.4634    267.0
82  multiclass  Ensemble: specialized hierarchical subtype  mostly-true     0.4290  0.5341    0.4758    249.0
83  multiclass  Ensemble: specialized hierarchical subtype         true     0.4894  0.3270    0.3920    211.0

[84 rows x 7 columns]